/** Pure Step 3 evaluator.  It consumes only admitted Step 2 values. */
import { deepFreezeClone, generateContextHealthDecisionRef, validateContextHealthDecisionSemantics, validateContextHealthEvaluationInputV1, validateContextHealthPolicyV1, type ContextHealthDecisionV1, type ContextHealthEvaluationInputV1, type ContextHealthPolicyV1, type DeepReadonly, type DerivedSignalRuleV1, type OutcomeV1 } from './index'

export type EvaluatorFailureReasonV1='policy_mismatch'|'unsupported_derived_rule_tuple'|'duplicate_derived_rule_tuple'|'invalid_threshold_kind_for_source'|'invalid_threshold_value'|'invalid_weight_for_signal_class'|'missing_atomic_mapping'|'atomic_mapping_mismatch'|'atomic_authority_mismatch'|'evidence_kind_not_permitted'|'missing_checkpoint_rule'|'duplicate_checkpoint_rule'|'unknown_handling_mismatch'
export type ContextHealthEvaluationResultV1={readonly ok:true;readonly decision:DeepReadonly<ContextHealthDecisionV1>}|{readonly ok:false;readonly reason:EvaluatorFailureReasonV1}
const severity:Record<OutcomeV1,number>={continue:0,checkpoint_only:1,handoff_required:2,hard_stop_and_handoff:3}
const table=new Set(['atomic_signal|operator_hard_stop|hard_stop|none','atomic_signal|operator_handoff|forced_handoff|none','atomic_signal|context_limit|forced_handoff|none','atomic_signal|compression_pressure_observed|soft|none','atomic_signal|role_reconstruction_warning|soft|none','atomic_signal|security_boundary_uncertain|hard_stop|none','atomic_signal|nonmandatory_retrieval_failure|soft|none','coverage|security_boundary_uncertain|hard_stop|none','coverage|nonmandatory_retrieval_failure|soft|count_at_least','counter|compression_pressure_observed|soft|count_at_least','counter|role_reconstruction_warning|soft|count_at_least','counter|nonmandatory_retrieval_failure|soft|count_at_least','validation|security_boundary_uncertain|hard_stop|none','validation|nonmandatory_retrieval_failure|soft|count_at_least','handoff|security_boundary_uncertain|hard_stop|none','handoff|nonmandatory_retrieval_failure|soft|count_at_least'])
const atomic:{readonly code:string;readonly derived:string;readonly cls:string;readonly authority:string}[]=[{code:'operator_hard_stop_event',derived:'operator_hard_stop',cls:'hard_stop',authority:'authoritative'},{code:'operator_handoff_event',derived:'operator_handoff',cls:'forced_handoff',authority:'authoritative'},{code:'user_context_limit_event',derived:'context_limit',cls:'forced_handoff',authority:'authoritative'},{code:'compression_event',derived:'compression_pressure_observed',cls:'soft',authority:'advisory'},{code:'role_reconstruction_warning_event',derived:'role_reconstruction_warning',cls:'soft',authority:'advisory'},{code:'security_uncertainty_event',derived:'security_boundary_uncertain',cls:'hard_stop',authority:'authoritative'},{code:'nonmandatory_retrieval_failure_event',derived:'nonmandatory_retrieval_failure',cls:'soft',authority:'advisory'}]
const key=(r:DerivedSignalRuleV1)=>`${r.source_kind}|${r.derived_signal_code}|${r.signal_class}|${r.threshold.kind}`
const max=(a:OutcomeV1,b:OutcomeV1)=>severity[a]>=severity[b]?a:b

function policyFailure(p:ContextHealthPolicyV1):EvaluatorFailureReasonV1|undefined{
  if(p.lifecycle_status!=='approved'||p.evaluator_contract_version!=='context-health-evaluator-v1')return 'policy_mismatch'
  const tuples=new Set<string>();for(const r of p.derived_signal_rules){const k=key(r);if(!table.has(k))return 'unsupported_derived_rule_tuple';if(tuples.has(k))return 'duplicate_derived_rule_tuple';tuples.add(k);if(r.threshold.kind==='count_at_least'&&(!Number.isInteger(r.threshold.value)||r.threshold.value<1))return 'invalid_threshold_value';if(r.signal_class==='soft'&&(!Number.isInteger(r.weight)||!r.weight||r.weight<1))return 'invalid_weight_for_signal_class';if(r.signal_class!=='soft'&&'weight'in r)return 'invalid_weight_for_signal_class'}
  for(const required of ['atomic_signal|security_boundary_uncertain|hard_stop|none','coverage|security_boundary_uncertain|hard_stop|none','validation|security_boundary_uncertain|hard_stop|none','handoff|security_boundary_uncertain|hard_stop|none'])if(!tuples.has(required))return 'missing_atomic_mapping'
  return undefined
}

export async function evaluateContextHealthV1(inputCandidate:unknown,policyCandidate:unknown):Promise<ContextHealthEvaluationResultV1>{
  const at=typeof (inputCandidate as {evaluation_timestamp?:unknown})?.evaluation_timestamp==='string'?(inputCandidate as {evaluation_timestamp:string}).evaluation_timestamp:''
  const inputAdmission=validateContextHealthEvaluationInputV1(inputCandidate,at);const policyAdmission=validateContextHealthPolicyV1(policyCandidate,at)
  if(!inputAdmission.accepted||!policyAdmission.accepted)return {ok:false,reason:'policy_mismatch'}
  const input=inputAdmission.value as ContextHealthEvaluationInputV1,policy=policyAdmission.value as ContextHealthPolicyV1
  if(input.policy_ref!==policy.context_health_policy_ref)return {ok:false,reason:'policy_mismatch'}
  const failure=policyFailure(policy);if(failure)return {ok:false,reason:failure}
  const checkpoint=policy.checkpoint_rules.filter(r=>r.checkpoint_type===input.checkpoint.checkpoint_type);if(checkpoint.length===0)return {ok:false,reason:'missing_checkpoint_rule'};if(checkpoint.length!==1)return {ok:false,reason:'duplicate_checkpoint_rule'}
  const atomicRefs:string[]=[],hard:string[]=[],forced:string[]=[],unknown:string[]=[],unknownRules:string[]=[],contrib:{rule_ref:string;derived_signal_code:string;weight:number;evidence_refs:unknown[]}[]=[]
  for(const row of atomic){const ar=policy.atomic_signal_rules.filter(r=>r.atomic_signal_code===row.code);if(ar.length>1)return {ok:false,reason:'missing_atomic_mapping'};const obs=input.atomic_signal_observations.filter(o=>o.atomic_signal_code===row.code);if(obs.length===0)continue;const rule=ar[0];if(!rule||rule.authority!==row.authority||rule.derived_signal_code!==row.derived)return {ok:false,reason:'atomic_mapping_mismatch'};if(obs.some(o=>o.authority!==row.authority||o.evidence_refs.some(e=>!rule.permitted_evidence_kinds.includes(e.kind))))return {ok:false,reason:'atomic_authority_mismatch'};const dr=policy.derived_signal_rules.find(r=>r.source_kind==='atomic_signal'&&r.derived_signal_code===row.derived&&r.signal_class===row.cls);if(!dr)return {ok:false,reason:'missing_atomic_mapping'};atomicRefs.push(rule.rule_ref);const present=obs.filter(o=>o.presence==='present');const hasUnknown=obs.some(o=>o.presence==='unknown');if(hasUnknown&&row.authority==='authoritative'){const security=policy.derived_signal_rules.find(r=>r.source_kind==='atomic_signal'&&r.derived_signal_code==='security_boundary_uncertain'&&r.signal_class==='hard_stop');if(!security)return {ok:false,reason:'missing_atomic_mapping'};hard.push(security.rule_ref);const u=policy.unknown_handling_rules.find(r=>r.evidence_class==='authoritative_signal'&&r.handling==='block');if(!u)return {ok:false,reason:'unknown_handling_mismatch'};unknownRules.push(u.rule_ref)}else if(hasUnknown&&row.authority==='advisory'){unknown.push(row.derived);const u=policy.unknown_handling_rules.find(r=>r.evidence_class==='advisory_signal'&&r.handling==='report_without_score');if(!u)return {ok:false,reason:'unknown_handling_mismatch'};unknownRules.push(u.rule_ref)}if(present.length){const evidence=[...new Map(present.flatMap(o=>o.evidence_refs).map(e=>[JSON.stringify(e),e])).values()];if(evidence.length===0)return {ok:false,reason:'evidence_kind_not_permitted'};if(row.cls==='hard_stop')hard.push(dr.rule_ref);else if(row.cls==='forced_handoff')forced.push(dr.rule_ref);else contrib.push({rule_ref:dr.rule_ref,derived_signal_code:dr.derived_signal_code,weight:dr.weight!,evidence_refs:evidence})}}
  const coverageRefs=policy.coverage_rules.filter(r=>r.applicable_checkpoint_types.includes(input.checkpoint.checkpoint_type));const required=new Set([...checkpoint[0].required_coverage_classes,...coverageRefs.filter(r=>r.required).map(r=>r.coverage_class)]);const coverage=input.canonical_record_coverage as any[];const coverageHard=[...required].some(c=>coverage.filter(x=>x.coverage_class===c).length!==1||coverage.some(x=>x.coverage_class===c&&x.verification_state!=='verified'))||coverage.some(x=>x.verification_state==='contradicted');const add=(r:any,e:any[])=>{if(r.signal_class==='hard_stop')hard.push(r.rule_ref);else if(r.signal_class==='forced_handoff')forced.push(r.rule_ref);else contrib.push({rule_ref:r.rule_ref,derived_signal_code:r.derived_signal_code,weight:r.weight,evidence_refs:e})};for(const r of policy.derived_signal_rules){if(r.source_kind==='coverage'){if(r.derived_signal_code==='security_boundary_uncertain'&&coverageHard)add(r,[]);if(r.derived_signal_code==='nonmandatory_retrieval_failure'&&!coverageHard&&coverage.filter(x=>!required.has(x.coverage_class)&&x.verification_state==='unavailable').length>=(r.threshold as any).value)add(r,[])}else if(r.source_kind==='counter'){const cs:any=input.counter_snapshot;const values=r.derived_signal_code==='compression_pressure_observed'?[cs.interaction_count,cs.operation_count,cs.dependency_count]:r.derived_signal_code==='role_reconstruction_warning'?[cs.unresolved_item_count,cs.active_blocker_count,cs.amendment_count,cs.settled_fact_correction_count,...cs.settled_fact_reexplanation_counts.map((x:any)=>x.count)]:cs.repeated_record_fetch_counts.map((x:any)=>x.count);if(values.some((n:number)=>n>=(r.threshold as any).value))add(r,[])}else if(r.source_kind==='validation'){const requiredRefs=input.constraint_snapshot.required_validation_refs as any[];const bindings=input.validation_bindings as any[];const bad=requiredRefs.some(ref=>bindings.filter(b=>JSON.stringify(b).includes(JSON.stringify(ref))).length!==1);if(r.derived_signal_code==='security_boundary_uncertain'&&input.checkpoint.blocking_class==='blocking'&&bad)add(r,[]);if(r.derived_signal_code==='nonmandatory_retrieval_failure'&&bindings.filter(b=>!['passed','not_applicable'].includes(b.state)).length>=(r.threshold as any).value)add(r,[])}else if(r.source_kind==='handoff'){const h:any=input.handoff_artifact;if(r.derived_signal_code==='security_boundary_uncertain'&&(h.state==='invalid'||(input.checkpoint.checkpoint_type==='post_result_handoff'&&h.state!=='complete')))add(r,[]);if(r.derived_signal_code==='nonmandatory_retrieval_failure'&&input.checkpoint.checkpoint_type!=='post_result_handoff'&&h.state==='unavailable'&&(r.threshold as any).value===1)add(r,[])}}
  let outcome:OutcomeV1=hard.length?'hard_stop_and_handoff':forced.length?'handoff_required':'continue';let score=0;if(!hard.length&&!forced.length){score=contrib.reduce((n,c)=>n+c.weight,0);const t=policy.outcome_thresholds;outcome=score>=t.handoff_required_min?'handoff_required':score>=t.checkpoint_only_min?'checkpoint_only':'continue'}
  const escalation=policy.consecutive_checkpoint_escalation;let escalationDecision:ContextHealthDecisionV1['checkpoint_escalation_evaluation']={state:'not_applicable',rule_ref:escalation.rule_ref,reason_code:'pre_escalation_outcome_not_checkpoint_only',pre_escalation_outcome:outcome};if(outcome==='checkpoint_only'&&escalation.state==='enabled'){const prior=input.prior_checkpoint.state==='available'?input.prior_checkpoint.prior_decision_refs:[];const count=input.prior_checkpoint.state==='available'?input.prior_checkpoint.consecutive_checkpoint_only:0;if(count>=escalation.consecutive_count_threshold){outcome=escalation.escalation_outcome;escalationDecision={state:'applied',rule_ref:escalation.rule_ref,pre_escalation_outcome:'checkpoint_only',prior_decision_refs:prior,observed_consecutive_count:escalation.consecutive_count_threshold,effective_outcome:'handoff_required'}}else escalationDecision={state:'not_applied',rule_ref:escalation.rule_ref,pre_escalation_outcome:'checkpoint_only',prior_decision_refs:prior,observed_consecutive_count:count,effective_outcome:'checkpoint_only'}}
  let override:ContextHealthDecisionV1['operator_override_evaluation']={state:'absent'};if(input.operator_override.state==='bound'){const o=input.operator_override;const effective=max(outcome,o.minimum_outcome);override={state:effective===outcome?'not_applied':'applied',override_ref:o.override_ref,actor_role:o.actor_role,authority_result:'authorized',requested_minimum_outcome:o.minimum_outcome,pre_override_outcome:outcome,effective_outcome:effective,override_rule_ref:policy.override_rule.rule_ref,reason_code:effective===outcome?'already_at_or_above_minimum':o.reason_code};outcome=effective}
  const decision:any={contract_version:'context-health-decision-v1',context_health_decision_ref:'evidence/context-health-decisions/sha256-'+ '0'.repeat(64),context_health_input_ref:input.context_health_input_ref,context_health_policy_ref:policy.context_health_policy_ref,task_id:input.task_id,assignment_revision:input.assignment_revision,role:input.role,repository:input.repository,workflow_phase:input.workflow_phase,checkpoint_instance_id:input.checkpoint.checkpoint_instance_id,checkpoint_type:input.checkpoint.checkpoint_type,outcome,legal_action_class:outcome==='continue'||outcome==='checkpoint_only'?'assigned_work_allowed':outcome==='handoff_required'?'handoff_required':'hard_stop',required_artifact_class:outcome==='continue'?'decision_record':'context_handoff_manifest',checkpoint_rule_ref:checkpoint[0].rule_ref,applied_atomic_signal_rule_refs:[...new Set(atomicRefs)].sort(),applied_coverage_rule_refs:[],hard_rule_refs:[...new Set(hard)].sort(),forced_handoff_rule_refs:[...new Set(forced)].sort(),soft_contributions:contrib.sort((a,b)=>a.rule_ref.localeCompare(b.rule_ref)),applied_unknown_handling_rule_refs:[...new Set(unknownRules)].sort(),checkpoint_escalation_evaluation:escalationDecision,operator_override_evaluation:override,unknown_advisory_signal_codes:[...new Set(unknown)].sort(),prior_decision_refs:input.prior_checkpoint.state==='available'?input.prior_checkpoint.prior_decision_refs:[],soft_score:hard.length||forced.length?0:score,evaluator_contract_version:'context-health-evaluator-v1',evaluation_timestamp:input.evaluation_timestamp};decision.context_health_decision_ref=await generateContextHealthDecisionRef(decision);if(!validateContextHealthDecisionSemantics(decision,policy).valid)return {ok:false,reason:'policy_mismatch'};return {ok:true,decision:deepFreezeClone(decision)}
}
