/** Step 4 pure Dispatcher/Role boundary.  It has no collector, publisher, or action executor. */
import { deepFreezeClone, validateCanonicalSourceRefV1, validateContextHealthDecisionSemantics, validateContextHealthDecisionV1, validateContextHealthEvaluationInputV1, validateContextHealthPolicyV1, verifyContextHealthReference, type CanonicalSourceRefV1, type ContextHealthDecisionV1, type ContextHealthEvaluationInputV1, type ContextHealthPolicyV1, type DeepReadonly, type RoleV1, type WorkflowPhaseV1 } from './index'
import { evaluateContextHealthV1 } from './evaluator'

export const REQUESTED_ACTIONS=['create_architecture_draft_pr','begin_review_judgment','route_recorded_review_decision','begin_amendment_implementation','modify_reviewed_branch','publish_revision_completion','accept_result_handoff','route_next_role','publish_integrated_report','recommend_merge','begin_post_merge_action','begin_next_phase_work','begin_reassigned_role_work','begin_production_defect_remediation_judgment','begin_large_dependency_task','publish_architecture_stream_closure','continue_current_assigned_work','record_periodic_observation','merge_pull_request','approve_pull_request','mark_pull_request_ready','revert_change','close_issue','change_product_scope','change_role_assignment'] as const
export type RequestedActionV1=typeof REQUESTED_ACTIONS[number]
export const INTEGRATION_FAILURE_CODES=['integration_request_invalid','policy_admission_failed','evaluation_input_admission_failed','required_identity_missing','required_checkpoint_data_missing','requested_action_reference_missing','task_assignment_identity_stale','requested_action_reference_stale','cross_input_identity_mismatch','policy_input_identity_mismatch','content_reference_mismatch','decision_identity_mismatch','requested_action_reference_mismatch','unsupported_role','unsupported_workflow_phase','unsupported_checkpoint_type','unsupported_requested_action','unsupported_decision_outcome','illegal_action_tuple','requested_action_exceeds_assignment','protected_action_forbidden','decision_action_conflict','evaluator_failed','decision_contract_invalid','decision_semantic_invalid','decision_reference_invalid','duplicate_integration_state','contradictory_integration_state','checkpoint_instruction_invalid','integration_internal_failure'] as const
export type IntegrationFailureCodeV1=typeof INTEGRATION_FAILURE_CODES[number]
export interface TaskAssignmentActionBindingV1 { readonly canonical_task_record:CanonicalSourceRefV1; readonly task_assignment_coverage_id:string; readonly task_assignment_immutable_revision:unknown; readonly task_id:string; readonly assignment_revision:number; readonly assigned_role:RoleV1; readonly repository:'whatrune/sd-prompt-studio'; readonly workflow_phase:WorkflowPhaseV1; readonly requested_action:RequestedActionV1; readonly requested_action_ref:CanonicalSourceRefV1 }
type Failure={readonly contract_version:'context-health-integration-result-v1';readonly context_health_integration_result_ref:string;readonly result_kind:'failure';readonly failure_code:IntegrationFailureCodeV1;readonly failure_stage:string;readonly path:string;readonly message:string;readonly verified_identity_refs:readonly CanonicalSourceRefV1[];readonly decision_owner:RoleV1;readonly retry_policy:string}
type Success={readonly contract_version:'context-health-integration-result-v1';readonly context_health_integration_result_ref:string;readonly result_kind:'continue'|'checkpoint_only'|'handoff_required'|'hard_stop_and_handoff';readonly result_reason_code:string;readonly canonical_task_record:CanonicalSourceRefV1;readonly task_assignment_immutable_revision:unknown;readonly task_id:string;readonly assignment_revision:number;readonly role:RoleV1;readonly repository:'whatrune/sd-prompt-studio';readonly workflow_phase:WorkflowPhaseV1;readonly checkpoint_instance_id:string;readonly checkpoint_type:string;readonly protected_action_ref:CanonicalSourceRefV1;readonly requested_action:RequestedActionV1;readonly requested_action_ref:CanonicalSourceRefV1;readonly context_health_policy_ref:string;readonly context_health_input_ref:string;readonly context_health_decision_ref:string;readonly checkpoint_rule_ref:string;readonly legal_next_action:string;readonly hard_rule_refs:readonly string[];readonly forced_handoff_rule_refs:readonly string[];readonly checkpoint_publication_instruction?:unknown;readonly handoff_boundary_instruction?:unknown}
export type ContextHealthIntegrationResultV1=Success|Failure
const protectedActions=new Set<RequestedActionV1>(['merge_pull_request','approve_pull_request','mark_pull_request_ready','revert_change','close_issue','change_product_scope','change_role_assignment'])
const roles:Record<string,readonly string[]>={integrated_lead:['intake','review','merge_decision','post_merge','research_review','reporting','support','closure'],architect_team:['architecture','review','revision','merge_decision','post_merge','support','closure'],backend_architect:['architecture','validation','review','revision','merge_decision','post_merge','support','closure'],backend_implementer:['implementation','validation','revision','post_merge','support'],frontend_implementer:['implementation','validation','revision','post_merge','support'],worker:['implementation','validation','research_execution','support'],research_execution_op:['research_execution','validation'],image_analysis_op:['research_execution','validation'],research_review_op:['research_review','validation'],maintenance_op:['research_execution','validation','post_merge','support'],reporting_op:['reporting','validation']}
const matrix:Record<string,readonly string[]>={architecture_draft_pr_creation:['create_architecture_draft_pr'],pre_review:['begin_review_judgment'],first_review_decision:['route_recorded_review_decision'],subsequent_review_decision:['route_recorded_review_decision'],review_amendment_creation:['begin_amendment_implementation'],pre_revision:['modify_reviewed_branch'],revision_completion:['publish_revision_completion'],post_result_handoff:['accept_result_handoff','route_next_role','publish_integrated_report'],pre_merge_recommendation:['recommend_merge'],merge_confirmation:['begin_post_merge_action'],phase_transition:['begin_next_phase_work'],specialist_reassignment:['begin_reassigned_role_work'],production_defect_discovery:['begin_production_defect_remediation_judgment'],large_dependency_task_start:['begin_large_dependency_task'],major_architecture_stream_close:['publish_architecture_stream_closure'],operator_requested:['continue_current_assigned_work'],periodic_observation:['record_periodic_observation']}
const owner=(code:IntegrationFailureCodeV1):[RoleV1,string]=>protectedActions.has(code as RequestedActionV1)?['product_owner','after_product_owner_decision']:['backend_implementer','after_implementation_fix']
const same=(a:CanonicalSourceRefV1,b:CanonicalSourceRefV1)=>JSON.stringify(a)===JSON.stringify(b)
async function ref(v:unknown){const s=JSON.stringify(v,Object.keys(v as object).sort());const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return 'evidence/context-health-integration-results/sha256-'+[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function failure(code:IntegrationFailureCodeV1,path:string,message:string,refs:CanonicalSourceRefV1[]=[]):Promise<DeepReadonly<Failure>>{const [decision_owner,retry_policy]=owner(code);const x:Failure={contract_version:'context-health-integration-result-v1',context_health_integration_result_ref:'',result_kind:'failure',failure_code:code,failure_stage:'identity_binding',path,message,verified_identity_refs:refs,decision_owner,retry_policy};return deepFreezeClone({...x,context_health_integration_result_ref:await ref(x)})}
export async function integrateContextHealthV1(bindingCandidate:unknown,inputCandidate:unknown,policyCandidate:unknown):Promise<DeepReadonly<ContextHealthIntegrationResultV1>>{
 const at=typeof (inputCandidate as any)?.evaluation_timestamp==='string'?(inputCandidate as any).evaluation_timestamp:''; const inputA=at&&validateContextHealthEvaluationInputV1(inputCandidate,at); if(!inputA||!inputA.accepted)return failure('evaluation_input_admission_failed','$','evaluation input admission failed'); const policyA=validateContextHealthPolicyV1(policyCandidate,at);if(!policyA.accepted)return failure('policy_admission_failed','$','policy admission failed'); const input=inputA.value as ContextHealthEvaluationInputV1,policy=policyA.value as ContextHealthPolicyV1,b=bindingCandidate as TaskAssignmentActionBindingV1;
 if(!b||typeof b!=='object'||!validateCanonicalSourceRefV1(b.canonical_task_record)||!REQUESTED_ACTIONS.includes(b.requested_action))return failure('integration_request_invalid','$','integration binding is invalid'); if(protectedActions.has(b.requested_action))return failure('protected_action_forbidden','$.requested_action','protected action is forbidden'); if(!roles[b.assigned_role]?.includes(b.workflow_phase))return failure('unsupported_role','$.assigned_role','role/phase is unsupported'); if(!matrix[input.checkpoint.checkpoint_type])return failure('unsupported_checkpoint_type','$.checkpoint','checkpoint is unsupported'); if(!matrix[input.checkpoint.checkpoint_type].includes(b.requested_action))return failure('illegal_action_tuple','$.requested_action','tuple is not legal'); if(!same(b.canonical_task_record,input.workflow_identity.canonical_task_record)||b.task_id!==input.task_id||b.assignment_revision!==input.assignment_revision||b.assigned_role!==input.role||b.workflow_phase!==input.workflow_phase||!same(b.requested_action_ref,input.checkpoint.protected_action_ref)||!input.constraint_snapshot.allowed_change_refs.some(x=>same(x,b.requested_action_ref))||input.constraint_snapshot.forbidden_change_refs.some(x=>same(x,b.requested_action_ref)))return failure('cross_input_identity_mismatch','$','identity binding mismatch',[b.canonical_task_record]);
 const e=await evaluateContextHealthV1(input,policy);if(!e.ok)return failure('evaluator_failed','$','evaluator failed',[b.canonical_task_record]);const d=e.decision as ContextHealthDecisionV1;if(!validateContextHealthDecisionV1(d,at).accepted||!validateContextHealthDecisionSemantics(d,policy).valid||!(await verifyContextHealthReference(d)))return failure('decision_reference_invalid','$','decision verification failed',[b.canonical_task_record]);const kind=d.outcome;const common:any={contract_version:'context-health-integration-result-v1',context_health_integration_result_ref:'',result_kind:kind,result_reason_code:kind==='continue'?'exact_assigned_action_authorized':kind==='checkpoint_only'?'checkpoint_record_required_before_exact_continuation':kind==='handoff_required'?'handoff_boundary_required':'hard_stop_and_handoff_boundary_required',canonical_task_record:b.canonical_task_record,task_assignment_immutable_revision:b.task_assignment_immutable_revision,task_id:b.task_id,assignment_revision:b.assignment_revision,role:b.assigned_role,repository:b.repository,workflow_phase:b.workflow_phase,checkpoint_instance_id:input.checkpoint.checkpoint_instance_id,checkpoint_type:input.checkpoint.checkpoint_type,protected_action_ref:input.checkpoint.protected_action_ref,requested_action:b.requested_action,requested_action_ref:b.requested_action_ref,context_health_policy_ref:policy.context_health_policy_ref,context_health_input_ref:input.context_health_input_ref,context_health_decision_ref:d.context_health_decision_ref,checkpoint_rule_ref:d.checkpoint_rule_ref,legal_next_action:kind==='continue'?'execute_exact_requested_action':kind==='checkpoint_only'?'follow_checkpoint_publication_instruction':'invoke_future_handoff_generation_boundary',hard_rule_refs:d.hard_rule_refs,forced_handoff_rule_refs:d.forced_handoff_rule_refs}; if(kind==='checkpoint_only')common.checkpoint_publication_instruction={instruction_kind:'construct_validate_publish_then_release_exact_action',publication_performed:false,deferred_requested_action:b.requested_action};if(kind==='handoff_required'||kind==='hard_stop_and_handoff')common.handoff_boundary_instruction={instruction_kind:'invoke_future_handoff_generation_boundary',publication_performed:false,continuation_state:kind==='hard_stop_and_handoff'?'all_continuation_blocked':'new_design_and_implementation_blocked'}; return deepFreezeClone({...common,context_health_integration_result_ref:await ref(common)})
}
