import { deepFreezeClone, type CanonicalSourceRefV1, type ComponentArtifactV1, type ContextHandoffManifestV1 } from '../index'

export const COMPONENT_KIND_ORDER=['compressed_context_handoff','bootstrap_prompt','canonical_record_manifest','repository_state_snapshot','validation_snapshot'] as const
export type ComponentKindV1=ComponentArtifactV1['component_kind']
export const COMPONENT_DESCRIPTOR_EVIDENCE_PROJECTION_VERSION='context-handoff-component-descriptor-evidence-v1' as const
export const COMPONENT_OBSERVED_BYTES_EVIDENCE_PROJECTION_VERSION='context-handoff-component-observed-bytes-evidence-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION='context-handoff-component-validation-production-outcome-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION='context-handoff-component-validation-production-failure-v1' as const
export const COMPONENT_VALIDATION_DIAGNOSTIC_IDENTITY_PROJECTION_VERSION='context-handoff-component-validation-diagnostic-identity-v1' as const

export interface DescriptorEvidenceProjectionV1 { readonly projection_contract_version:typeof COMPONENT_DESCRIPTOR_EVIDENCE_PROJECTION_VERSION; readonly context_handoff_manifest_ref:string; readonly component_kind:ComponentKindV1; readonly component_id:string; readonly content_type:'application/json'; readonly byte_length:number; readonly sha256:string }
export interface ObservedBytesEvidenceProjectionV1 { readonly projection_contract_version:typeof COMPONENT_OBSERVED_BYTES_EVIDENCE_PROJECTION_VERSION; readonly context_handoff_manifest_ref:string; readonly component_kind:ComponentKindV1; readonly computed_byte_length:number; readonly computed_sha256:string }
export type ComponentValidationProductionOutcomeV1={readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION;readonly outcome_kind:'produced';readonly component_validation_result:import('../index').ContextHandoffComponentValidationResultV1;readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:string}|{readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION;readonly outcome_kind:'rejected';readonly structural_rejection:{readonly contract_version:'context-health-structural-rejection-v1';readonly code:string;readonly path:string;readonly message:string;readonly observed_at:string};readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:string}|{readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION;readonly outcome_kind:'failed';readonly failure:ComponentValidationProductionFailureV1;readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:string}
export interface ComponentValidationProductionFailureV1 { readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION; readonly failure_code:'component_validation_production_internal_failure'; readonly path:string; readonly message:'component validation production failed internally'; readonly evidence_refs:readonly CanonicalSourceRefV1[]; readonly validator_contract_version:'context-handoff-component-validator-v1'; readonly observed_at:string }

const utf8=new TextEncoder()
const isObject=(value:unknown):value is {[key:string]:unknown}=>typeof value==='object'&&value!==null&&!Array.isArray(value)
const jcs=(value:unknown):string=>{if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(jcs).join(',')}]`;if(isObject(value))return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${jcs(value[key])}`).join(',')}}`;throw new TypeError('outside JSON')}
const sha=async(value:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',utf8.encode(value)))].map(byte=>byte.toString(16).padStart(2,'0')).join('')
const content=(prefix:string, value:unknown)=>sha(jcs(value)).then(hash=>`${prefix}/sha256-${hash}`)
const canonical=(refs:readonly CanonicalSourceRefV1[])=>[...refs].sort((left,right)=>jcs(left).localeCompare(jcs(right)))

export const descriptorEvidenceProjectionV1=(manifest:ContextHandoffManifestV1,descriptor:ComponentArtifactV1):DescriptorEvidenceProjectionV1=>deepFreezeClone({projection_contract_version:COMPONENT_DESCRIPTOR_EVIDENCE_PROJECTION_VERSION,context_handoff_manifest_ref:manifest.context_handoff_manifest_ref,component_kind:descriptor.component_kind,component_id:descriptor.component_id,content_type:descriptor.content_type,byte_length:descriptor.byte_length,sha256:descriptor.sha256})
export const observedBytesEvidenceProjectionV1=(manifest:ContextHandoffManifestV1,kind:ComponentKindV1,length:number,digest:string):ObservedBytesEvidenceProjectionV1=>deepFreezeClone({projection_contract_version:COMPONENT_OBSERVED_BYTES_EVIDENCE_PROJECTION_VERSION,context_handoff_manifest_ref:manifest.context_handoff_manifest_ref,component_kind:kind,computed_byte_length:length,computed_sha256:digest})
export const generateDescriptorEvidenceRefV1=async(manifest:ContextHandoffManifestV1,descriptor:ComponentArtifactV1):Promise<CanonicalSourceRefV1>=>deepFreezeClone({kind:'content_addressed',content_ref:await content('evidence/context-handoff-component-descriptors',descriptorEvidenceProjectionV1(manifest,descriptor))})
export const generateObservedBytesEvidenceRefV1=async(manifest:ContextHandoffManifestV1,kind:ComponentKindV1,length:number,digest:string):Promise<CanonicalSourceRefV1>=>deepFreezeClone({kind:'content_addressed',content_ref:await content('evidence/context-handoff-component-observations',observedBytesEvidenceProjectionV1(manifest,kind,length,digest))})
export const generateComponentValidationDiagnosticIdV1=async(value:Omit<import('../index').ComponentValidationDiagnosticV1,'diagnostic_id'>):Promise<string>=>`diagnostics/context-handoff-component-validation/sha256-${await sha(jcs({projection_contract_version:COMPONENT_VALIDATION_DIAGNOSTIC_IDENTITY_PROJECTION_VERSION,component_kind:value.component_kind,code:value.code,path:value.path,message:value.message,evidence_refs:canonical(value.evidence_refs)}))}`
export const verifyComponentValidationDiagnosticIdV1=async(value:import('../index').ComponentValidationDiagnosticV1):Promise<boolean>=>value.diagnostic_id===await generateComponentValidationDiagnosticIdV1(value)
