import { canonicalContextHealthPropertyPathV1, createContextHealthStructuralRejectionV1, deepFreezeClone, validateContextHandoffComponentValidationInputV1, validateContextHandoffComponentValidationResultV1, validateContextHealthStructuralRejectionV1, verifyContextHandoffManifestRef, type AdmissionResult, type CanonicalSourceRefV1, type ComponentArtifactV1, type ContextHandoffManifestV1, type StrictUtcTimestampV1 } from '../index'

export const COMPONENT_KIND_ORDER=['compressed_context_handoff','bootstrap_prompt','canonical_record_manifest','repository_state_snapshot','validation_snapshot'] as const
export type ComponentKindV1=ComponentArtifactV1['component_kind']
export const COMPONENT_DESCRIPTOR_EVIDENCE_PROJECTION_VERSION='context-handoff-component-descriptor-evidence-v1' as const
export const COMPONENT_OBSERVED_BYTES_EVIDENCE_PROJECTION_VERSION='context-handoff-component-observed-bytes-evidence-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION='context-handoff-component-validation-production-outcome-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION='context-handoff-component-validation-production-failure-v1' as const
export const COMPONENT_VALIDATION_DIAGNOSTIC_IDENTITY_PROJECTION_VERSION='context-handoff-component-validation-diagnostic-identity-v1' as const

export interface DescriptorEvidenceProjectionV1 { readonly projection_contract_version:typeof COMPONENT_DESCRIPTOR_EVIDENCE_PROJECTION_VERSION; readonly context_handoff_manifest_ref:string; readonly component_kind:ComponentKindV1; readonly component_id:string; readonly content_type:'application/json'; readonly byte_length:number; readonly sha256:string }
export interface ObservedBytesEvidenceProjectionV1 { readonly projection_contract_version:typeof COMPONENT_OBSERVED_BYTES_EVIDENCE_PROJECTION_VERSION; readonly context_handoff_manifest_ref:string; readonly component_kind:ComponentKindV1; readonly computed_byte_length:number; readonly computed_sha256:string }
export type ComponentValidationProductionOutcomeV1={readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION;readonly outcome_kind:'produced';readonly component_validation_result:import('../index').ContextHandoffComponentValidationResultV1;readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:string}|{readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION;readonly outcome_kind:'rejected';readonly structural_rejection:{readonly contract_version:'context-health-structural-rejection-v1';readonly code:string;readonly path:string;readonly message:string;readonly observed_at:string};readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:string}|{readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION;readonly outcome_kind:'failed';readonly failure:ComponentValidationProductionFailureV1;readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:string}
export interface ComponentValidationProductionFailureV1 { readonly contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION; readonly failure_code:'component_validation_production_internal_failure'; readonly path:string; readonly message:'component validation production failed internally'; readonly evidence_refs:readonly CanonicalSourceRefV1[]; readonly validator_contract_version:'context-handoff-component-validator-v1'; readonly observed_at:string }

const utf8=new TextEncoder()
const isObject=(value:unknown):value is {[key:string]:unknown}=>typeof value==='object'&&value!==null&&!Array.isArray(value)
const jcs=(value:unknown):string=>{if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(jcs).join(',')}]`;if(isObject(value))return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${jcs(value[key])}`).join(',')}}`;throw new TypeError('outside JSON')}
const sha=async(value:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',utf8.encode(value)))].map(byte=>byte.toString(16).padStart(2,'0')).join('')
const content=(prefix:string, value:unknown)=>sha(jcs(value)).then(hash=>`${prefix}/sha256-${hash}`)
const canonical=(refs:readonly CanonicalSourceRefV1[])=>[...refs].sort((left,right)=>jcs(left).localeCompare(jcs(right)))

export const descriptorEvidenceProjectionV1=(manifest:ContextHandoffManifestV1,descriptor:ComponentArtifactV1):DescriptorEvidenceProjectionV1=>deepFreezeClone({projection_contract_version:COMPONENT_DESCRIPTOR_EVIDENCE_PROJECTION_VERSION,context_handoff_manifest_ref:manifest.context_handoff_manifest_ref,component_kind:descriptor.component_kind,component_id:descriptor.component_id,content_type:descriptor.content_type,byte_length:descriptor.byte_length,sha256:descriptor.sha256})
export const observedBytesEvidenceProjectionV1=(manifest:ContextHandoffManifestV1,kind:ComponentKindV1,length:number,digest:string):ObservedBytesEvidenceProjectionV1=>deepFreezeClone({projection_contract_version:COMPONENT_OBSERVED_BYTES_EVIDENCE_PROJECTION_VERSION,context_handoff_manifest_ref:manifest.context_handoff_manifest_ref,component_kind:kind,computed_byte_length:length,computed_sha256:digest})
export const generateDescriptorEvidenceRefV1=async(manifest:ContextHandoffManifestV1,descriptor:ComponentArtifactV1):Promise<CanonicalSourceRefV1>=>deepFreezeClone({kind:'content_addressed',content_ref:await content('evidence/context-handoff-component-descriptors',descriptorEvidenceProjectionV1(manifest,descriptor))})
export const generateObservedBytesEvidenceRefV1=async(manifest:ContextHandoffManifestV1,kind:ComponentKindV1,length:number,digest:string):Promise<CanonicalSourceRefV1>=>deepFreezeClone({kind:'content_addressed',content_ref:await content('evidence/context-handoff-component-observations',observedBytesEvidenceProjectionV1(manifest,kind,length,digest))})
export const generateComponentValidationDiagnosticIdV1=async(value:Omit<import('../index').ComponentValidationDiagnosticV1,'diagnostic_id'>):Promise<string>=>`diagnostics/context-handoff-component-validation/sha256-${await sha(jcs({projection_contract_version:COMPONENT_VALIDATION_DIAGNOSTIC_IDENTITY_PROJECTION_VERSION,component_kind:value.component_kind,code:value.code,path:value.path,message:value.message,evidence_refs:canonical(value.evidence_refs)}))}`
export const verifyComponentValidationDiagnosticIdV1=async(value:import('../index').ComponentValidationDiagnosticV1):Promise<boolean>=>value.diagnostic_id===await generateComponentValidationDiagnosticIdV1(value)
const rejectOutcome=(code:Parameters<typeof createContextHealthStructuralRejectionV1>[0],path:string,at:StrictUtcTimestampV1)=>({accepted:false as const,rejection:createContextHealthStructuralRejectionV1(code,path,at)})
const byteCompare=(left:string,right:string)=>{const a=utf8.encode(left),b=utf8.encode(right);for(let i=0;i<Math.min(a.length,b.length);i++){const d=a[i]-b[i];if(d)return d}return a.length-b.length}
const firstUnknown=(value:{[key:string]:unknown},allowed:readonly string[])=>Object.keys(value).filter(key=>!allowed.includes(key)).sort(byteCompare)[0]
export async function validateComponentValidationProductionFailureV1(value:unknown,sourceInput:unknown,observedAt:StrictUtcTimestampV1):Promise<AdmissionResult<ComponentValidationProductionFailureV1>>{const source=validateContextHandoffComponentValidationInputV1(sourceInput,observedAt);if(!source.accepted)return rejectOutcome('invalid_format','$',observedAt);const verification=await verifyContextHandoffManifestRef(source.value.context_handoff_manifest,observedAt);if(verification.result_kind==='mismatch')return rejectOutcome('content_reference_mismatch','$.context_handoff_manifest.context_handoff_manifest_ref',observedAt);if(verification.result_kind==='internal_failure'){if(typeof value!=='object'||value===null||Array.isArray(value))return rejectOutcome('not_object','$',observedAt);const x=value as {[key:string]:unknown};return x.contract_version===COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION&&x.failure_code==='component_validation_production_internal_failure'&&x.path==='$.context_handoff_manifest.context_handoff_manifest_ref'&&x.message==='component validation production failed internally'&&Array.isArray(x.evidence_refs)&&x.evidence_refs.length===0&&x.validator_contract_version==='context-handoff-component-validator-v1'&&x.observed_at===observedAt?{accepted:true,value:deepFreezeClone(x as unknown as ComponentValidationProductionFailureV1)}:rejectOutcome('invalid_conditional_fields','$.failure',observedAt)}if(typeof value!=='object'||value===null||Array.isArray(value))return rejectOutcome('not_object','$',observedAt);const x=value as {[key:string]:unknown},fields=['contract_version','failure_code','path','message','evidence_refs','validator_contract_version','observed_at'];if(Object.keys(x).length!==fields.length||!fields.every(k=>k in x)||x.contract_version!==COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION||x.failure_code!=='component_validation_production_internal_failure'||x.message!=='component validation production failed internally'||x.validator_contract_version!=='context-handoff-component-validator-v1'||x.observed_at!==observedAt||!Array.isArray(x.evidence_refs))return rejectOutcome('invalid_format','$',observedAt);return {accepted:true,value:deepFreezeClone({contract_version:COMPONENT_VALIDATION_PRODUCTION_FAILURE_VERSION,failure_code:'component_validation_production_internal_failure',path:typeof x.path==='string'?x.path:'$',message:'component validation production failed internally',evidence_refs:x.evidence_refs as CanonicalSourceRefV1[],validator_contract_version:'context-handoff-component-validator-v1',observed_at:observedAt})}}
export async function validateComponentValidationProductionOutcomeV1(value:unknown,sourceInput:unknown,observedAt:StrictUtcTimestampV1):Promise<AdmissionResult<ComponentValidationProductionOutcomeV1>>{
 const source=validateContextHandoffComponentValidationInputV1(sourceInput,observedAt)
 const verification=source.accepted?await verifyContextHandoffManifestRef(source.value.context_handoff_manifest,observedAt):undefined
 if(typeof value!=='object'||value===null||Array.isArray(value))return rejectOutcome('not_object','$',observedAt)
 const x=value as {[key:string]:unknown}
 if(!source.accepted||verification?.result_kind==='mismatch'){
  const expected=!source.accepted?source.rejection:createContextHealthStructuralRejectionV1('content_reference_mismatch','$.context_handoff_manifest.context_handoff_manifest_ref',observedAt)
  const path=!source.accepted?'$.sourceInput':'$.context_handoff_manifest.context_handoff_manifest_ref'
  if(x.outcome_kind==='rejected'&&validateContextHealthStructuralRejectionV1(x.structural_rejection,observedAt).accepted&&JSON.stringify(x.structural_rejection)===JSON.stringify(expected))return {accepted:true,value:deepFreezeClone(value as ComponentValidationProductionOutcomeV1)}
  return rejectOutcome('invalid_conditional_fields',path,observedAt)
 }
 if(verification?.result_kind==='internal_failure'){
  if(x.outcome_kind!=='failed')return rejectOutcome('invalid_conditional_fields','$.outcome_kind',observedAt)
  const failure=await validateComponentValidationProductionFailureV1(x.failure,sourceInput,observedAt)
  return failure.accepted?{accepted:true,value:deepFreezeClone(value as ComponentValidationProductionOutcomeV1)}:rejectOutcome('invalid_conditional_fields','$.failure',observedAt)
 }
 if(x.contract_version!==COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION)return rejectOutcome('invalid_conditional_fields','$.contract_version',observedAt)
 if(x.validator_contract_version!=='context-handoff-component-validator-v1')return rejectOutcome('invalid_conditional_fields','$.validator_contract_version',observedAt)
 if(x.observed_at!==observedAt)return rejectOutcome('invalid_conditional_fields','$.observed_at',observedAt)
 if(x.outcome_kind==='produced'){
  const result=validateContextHandoffComponentValidationResultV1(x.component_validation_result,observedAt)
  return result.accepted?{accepted:true,value:deepFreezeClone(value as ComponentValidationProductionOutcomeV1)}:rejectOutcome('invalid_conditional_fields','$.component_validation_result',observedAt)
 }
 if(x.outcome_kind==='failed'){
  const failure=await validateComponentValidationProductionFailureV1(x.failure,sourceInput,observedAt)
  return failure.accepted?{accepted:true,value:deepFreezeClone(value as ComponentValidationProductionOutcomeV1)}:rejectOutcome('invalid_conditional_fields','$.failure',observedAt)
 }
 return rejectOutcome('invalid_enum','$.outcome_kind',observedAt)
}

export const COMPONENT_VALIDATION_TERMINAL_ANCHOR_FAILURE_VERSION='context-handoff-component-validation-terminal-anchor-failure-v1' as const
export const COMPONENT_VALIDATION_TERMINAL_ANCHOR_OUTCOME_VERSION='context-handoff-component-validation-terminal-anchor-outcome-v1' as const
export type ComponentValidationTerminalAnchorFailureV1={readonly contract_version:typeof COMPONENT_VALIDATION_TERMINAL_ANCHOR_FAILURE_VERSION;readonly failure_code:'component_validation_terminal_anchor_internal_failure';readonly path:'$';readonly message:'component validation returned the pre-admitted terminal fallback';readonly evidence_refs:readonly CanonicalSourceRefV1[];readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:StrictUtcTimestampV1}
export type ComponentValidationTerminalAnchorOutcomeV1={readonly contract_version:typeof COMPONENT_VALIDATION_TERMINAL_ANCHOR_OUTCOME_VERSION;readonly outcome_kind:'terminal_failed';readonly failure:ComponentValidationTerminalAnchorFailureV1;readonly validator_contract_version:'context-handoff-component-validator-v1';readonly observed_at:StrictUtcTimestampV1}
export type ComponentValidationProducerOutcomeV1=ComponentValidationProductionOutcomeV1|ComponentValidationTerminalAnchorOutcomeV1
export type ComponentValidationProductionFaultPointV1='throw_after_input_admission'|'invalidate_failure_before_failure_admission'|'invalidate_failed_wrapper_before_outcome_admission'|'throw_at_manifest_verifier_call_boundary'|'reject_manifest_verifier_promise_at_call_boundary'
export const COMPONENT_VALIDATION_PRODUCTION_FAULT_POINTS_V1=['throw_after_input_admission','invalidate_failure_before_failure_admission','invalidate_failed_wrapper_before_outcome_admission','throw_at_manifest_verifier_call_boundary','reject_manifest_verifier_promise_at_call_boundary'] as const
export type ComponentValidationProductionExecutionControlV1={readonly contract_version:'component-validation-production-execution-control-v1';readonly mode:'production'}|{readonly contract_version:'component-validation-production-execution-control-v1';readonly mode:'normative_test';readonly fault_point:ComponentValidationProductionFaultPointV1;readonly test_contract_version:'component-validation-production-normative-test-v1'}
const anchorFailureFields=['contract_version','failure_code','path','message','evidence_refs','validator_contract_version','observed_at'] as const
const anchorOutcomeFields=['contract_version','outcome_kind','failure','validator_contract_version','observed_at'] as const
const closed=(x:{[key:string]:unknown},fields:readonly string[])=>Object.keys(x).length===fields.length&&fields.every(field=>Object.prototype.hasOwnProperty.call(x,field)&&x[field]!==undefined)
export async function validateComponentValidationTerminalAnchorFailureV1(value:unknown,sourceInput:unknown,observedAt:StrictUtcTimestampV1):Promise<AdmissionResult<ComponentValidationTerminalAnchorFailureV1>>{const source=validateContextHandoffComponentValidationInputV1(sourceInput,observedAt);if(!source.accepted)return source;if(!isObject(value))return rejectOutcome(value===null?'null_forbidden':'not_object','$',observedAt);if(!closed(value,anchorFailureFields))return rejectOutcome('invalid_conditional_fields','$',observedAt);const x=value;return x.contract_version===COMPONENT_VALIDATION_TERMINAL_ANCHOR_FAILURE_VERSION&&x.failure_code==='component_validation_terminal_anchor_internal_failure'&&x.path==='$'&&x.message==='component validation returned the pre-admitted terminal fallback'&&Array.isArray(x.evidence_refs)&&x.evidence_refs.length===0&&x.validator_contract_version==='context-handoff-component-validator-v1'&&x.observed_at===observedAt?{accepted:true,value:deepFreezeClone(x as unknown as ComponentValidationTerminalAnchorFailureV1)}:rejectOutcome('invalid_conditional_fields','$',observedAt)}
export async function validateComponentValidationTerminalAnchorOutcomeV1(value:unknown,sourceInput:unknown,observedAt:StrictUtcTimestampV1):Promise<AdmissionResult<ComponentValidationTerminalAnchorOutcomeV1>>{if(!isObject(value))return rejectOutcome(value===null?'null_forbidden':'not_object','$',observedAt);if(!closed(value,anchorOutcomeFields)||value.contract_version!==COMPONENT_VALIDATION_TERMINAL_ANCHOR_OUTCOME_VERSION||value.outcome_kind!=='terminal_failed'||value.validator_contract_version!=='context-handoff-component-validator-v1'||value.observed_at!==observedAt)return rejectOutcome('invalid_conditional_fields','$',observedAt);const failure=await validateComponentValidationTerminalAnchorFailureV1(value.failure,sourceInput,observedAt);return failure.accepted?{accepted:true,value:deepFreezeClone({contract_version:COMPONENT_VALIDATION_TERMINAL_ANCHOR_OUTCOME_VERSION,outcome_kind:'terminal_failed',failure:failure.value,validator_contract_version:'context-handoff-component-validator-v1',observed_at:observedAt})}:failure}
export async function validateComponentValidationProducerOutcomeV1(value:unknown,sourceInput:unknown,observedAt:StrictUtcTimestampV1):Promise<AdmissionResult<ComponentValidationProducerOutcomeV1>>{if(!isObject(value))return rejectOutcome(value===null?'null_forbidden':'not_object','$',observedAt);if(value.contract_version===COMPONENT_VALIDATION_TERMINAL_ANCHOR_OUTCOME_VERSION)return validateComponentValidationTerminalAnchorOutcomeV1(value,sourceInput,observedAt);if(value.contract_version===COMPONENT_VALIDATION_PRODUCTION_OUTCOME_VERSION)return validateComponentValidationProductionOutcomeV1(value,sourceInput,observedAt);return rejectOutcome('unsupported_contract_version','$.contract_version',observedAt)}

export const COMPONENT_VALIDATION_PRODUCTION_SOURCE_ADMISSION_PROJECTION_VERSION='component-validation-production-source-admission-projection-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_VERSION='component-validation-production-test-evidence-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_FACTORY_INPUT_VERSION='component-validation-production-test-evidence-factory-input-v1' as const
export const COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_CAPTURE_MODES_V1=['record','force_capture_internal_failure_on_first_record','force_malformed_preclaim_prefix','force_journal_transfer_failure'] as const
export const COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_FAULT_POINTS_V1=['throw_after_input_admission','invalidate_failure_before_failure_admission','invalidate_failed_wrapper_before_outcome_admission'] as const
export type ComponentValidationProductionTestEvidenceFaultPointV1=typeof COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_FAULT_POINTS_V1[number]
export type ComponentValidationProductionTestEvidenceCaptureModeV1=typeof COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_CAPTURE_MODES_V1[number]
export type ComponentValidationProductionSourceAdmissionProjectionV1=Readonly<{projection_contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_SOURCE_ADMISSION_PROJECTION_VERSION;admission_stage:'source_input_structural_admission';accepted:true;observed_at:StrictUtcTimestampV1}>|Readonly<{projection_contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_SOURCE_ADMISSION_PROJECTION_VERSION;admission_stage:'source_input_structural_admission';accepted:false;rejection_code:Parameters<typeof createContextHealthStructuralRejectionV1>[0];rejection_path:string;observed_at:StrictUtcTimestampV1}>
export type ComponentValidationProductionTestAdmissionBoundaryV1='source_input_admission'|'terminal_anchor_failure_admission'|'producer_union_anchor_admission'|'production_failure_admission'|'production_outcome_admission'
export type ComponentValidationProductionTestAdmissionObservationV1=Readonly<{boundary:'source_input_admission';admission_projection:ComponentValidationProductionSourceAdmissionProjectionV1}>|Readonly<{boundary:Exclude<ComponentValidationProductionTestAdmissionBoundaryV1,'source_input_admission'>;admission_result:import('../index').DeepReadonly<AdmissionResult<unknown>>}>
export type ComponentValidationProductionTestTraceEventV1='source_input_admission_started'|'source_input_admission_accepted'|'terminal_anchor_failure_admission_started'|'terminal_anchor_failure_admission_accepted'|'producer_union_anchor_admission_started'|'producer_union_anchor_admission_accepted'|'terminal_anchor_retained'|'manifest_verification_started'|'manifest_verification_matched'|'fault_throw_after_input_admission_reached'|'invalid_primary_failure_constructed'|'primary_failure_constructed'|'production_failure_admission_started'|'production_failure_admission_accepted'|'production_failure_admission_rejected'|'invalid_failed_wrapper_constructed'|'production_outcome_admission_started'|'production_outcome_admission_rejected'|'post_anchor_exception_caught'|'fallback_selected'|'retained_anchor_returned'
export type ComponentValidationProductionTestBoundaryCallCountsV1=Readonly<{source_input_admission:number;terminal_anchor_failure_admission:number;producer_union_anchor_admission:number;manifest_verifier:number;production_failure_admission:number;production_outcome_admission:number;fallback_entry:number;post_fallback_operation:number}>
export type ComponentValidationProductionTestEvidenceControlV1=Extract<ComponentValidationProductionExecutionControlV1,{mode:'normative_test'}>
export type ComponentValidationProductionTestEvidenceFactoryInputV1=Readonly<{contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_FACTORY_INPUT_VERSION;fault_point:ComponentValidationProductionTestEvidenceFaultPointV1;capture_mode:ComponentValidationProductionTestEvidenceCaptureModeV1}>
export type ComponentValidationProductionTestEvidenceSingleUseTokenV1=Readonly<{contract_version:'component-validation-production-test-evidence-single-use-token-v1';observed_at:StrictUtcTimestampV1}>
export type ComponentValidationProductionTestEvidenceSessionV1=Readonly<{contract_version:'component-validation-production-test-evidence-session-v1';execution_control:ComponentValidationProductionTestEvidenceControlV1;single_use_token:ComponentValidationProductionTestEvidenceSingleUseTokenV1}>
export type ComponentValidationProductionTestEvidenceV1=Readonly<{contract_version:typeof COMPONENT_VALIDATION_PRODUCTION_TEST_EVIDENCE_VERSION;fault_point:ComponentValidationProductionTestEvidenceFaultPointV1;observed_at:StrictUtcTimestampV1;ordered_trace:readonly ComponentValidationProductionTestTraceEventV1[];boundary_call_counts:ComponentValidationProductionTestBoundaryCallCountsV1;intermediate_admission_results:readonly ComponentValidationProductionTestAdmissionObservationV1[];retained_anchor:ComponentValidationTerminalAnchorOutcomeV1;returned_retained_anchor:true;fallback_depth:1;retry_count:0}>
export type ComponentValidationProductionTestEvidenceCaptureDiagnosticV1=Readonly<{code:'component_validation_test_evidence_capture_internal_failure';path:'$.test_evidence_capture';message:'component validation test evidence capture failed internally'}>
export type ComponentValidationProductionTestEvidenceReadResultV1=Readonly<{contract_version:'component-validation-production-test-evidence-read-v1';result_kind:'unavailable';reason_code:'not_factory_owned'}>|Readonly<{contract_version:'component-validation-production-test-evidence-read-v1';result_kind:'not_started'|'running';observed_at:StrictUtcTimestampV1}>|Readonly<{contract_version:'component-validation-production-test-evidence-read-v1';result_kind:'completed';observed_at:StrictUtcTimestampV1;evidence:ComponentValidationProductionTestEvidenceV1}>|Readonly<{contract_version:'component-validation-production-test-evidence-read-v1';result_kind:'capture_internal_failure';observed_at:StrictUtcTimestampV1;diagnostic:ComponentValidationProductionTestEvidenceCaptureDiagnosticV1;fallback_depth:1;retry_count:0}>
