import { createContextHealthStructuralRejectionV1, deepFreezeClone, validateContextHandoffComponentValidationInputV1, validateContextHandoffComponentValidationResultV1, verifyContextHandoffManifestRef, EXPECTED_COMPONENT_CONTRACT_VERSIONS, type ComponentValidationDiagnosticV1, type ComponentValidationEntryV1, type StrictUtcTimestampV1 } from '../index'
import { validateCanonicalRecordManifestPayloadV1, validateCompressedContextHandoffPayloadV1, validateContextBootstrapPromptPayloadV1, validateRepositoryStateSnapshotPayloadV1, validateValidationSnapshotPayloadV1 } from '../artifacts/contracts'
import { COMPONENT_KIND_ORDER, generateComponentValidationDiagnosticIdV1, generateDescriptorEvidenceRefV1, generateObservedBytesEvidenceRefV1, validateComponentValidationProductionOutcomeV1, type ComponentKindV1, type ComponentValidationProductionOutcomeV1 } from './contracts'

const utc=(value:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)
const b64=/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/
const hash=async(bytes:Uint8Array)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource))].map(byte=>byte.toString(16).padStart(2,'0')).join('')
const decoder=new TextDecoder('utf-8',{fatal:true})
const validators:Readonly<Record<ComponentKindV1,(value:unknown)=>boolean>>={compressed_context_handoff:validateCompressedContextHandoffPayloadV1,bootstrap_prompt:validateContextBootstrapPromptPayloadV1,canonical_record_manifest:validateCanonicalRecordManifestPayloadV1,repository_state_snapshot:validateRepositoryStateSnapshotPayloadV1,validation_snapshot:validateValidationSnapshotPayloadV1}
const reject=(observed_at:string,path:string,code='invalid_format'):ComponentValidationProductionOutcomeV1=>deepFreezeClone({contract_version:'context-handoff-component-validation-production-outcome-v1',outcome_kind:'rejected',structural_rejection:{contract_version:'context-health-structural-rejection-v1',code,path,message:'component validation input is invalid',observed_at},validator_contract_version:'context-handoff-component-validator-v1',observed_at})

export async function produceContextHandoffComponentValidationResultV1(value:unknown,observedAt:StrictUtcTimestampV1):Promise<ComponentValidationProductionOutcomeV1>{
 try{
  if(!utc(observedAt))return reject(observedAt,'$.validation_timestamp','invalid_timestamp')
  const admission=validateContextHandoffComponentValidationInputV1(value,observedAt)
  if(!admission.accepted)return deepFreezeClone({contract_version:'context-handoff-component-validation-production-outcome-v1',outcome_kind:'rejected',structural_rejection:admission.rejection,validator_contract_version:'context-handoff-component-validator-v1',observed_at:observedAt})
  const input=admission.value;const manifest=input.context_handoff_manifest
  const manifestVerification=await verifyContextHandoffManifestRef(manifest,observedAt)
  if(manifestVerification.result_kind==='mismatch'){const candidate={contract_version:'context-handoff-component-validation-production-outcome-v1' as const,outcome_kind:'rejected' as const,structural_rejection:createContextHealthStructuralRejectionV1('content_reference_mismatch','$.context_handoff_manifest.context_handoff_manifest_ref',observedAt),validator_contract_version:'context-handoff-component-validator-v1' as const,observed_at:observedAt};const outcomeAdmission=await validateComponentValidationProductionOutcomeV1(candidate,value,observedAt);if(!outcomeAdmission.accepted)throw new Error('component validation production invariant failure');return outcomeAdmission.value}
  if(manifestVerification.result_kind==='internal_failure'){const candidate={contract_version:'context-handoff-component-validation-production-outcome-v1' as const,outcome_kind:'failed' as const,failure:{contract_version:'context-handoff-component-validation-production-failure-v1' as const,failure_code:'component_validation_production_internal_failure' as const,path:'$.context_handoff_manifest.context_handoff_manifest_ref',message:'component validation production failed internally' as const,evidence_refs:[],validator_contract_version:'context-handoff-component-validator-v1' as const,observed_at:observedAt},validator_contract_version:'context-handoff-component-validator-v1' as const,observed_at:observedAt};const outcomeAdmission=await validateComponentValidationProductionOutcomeV1(candidate,value,observedAt);if(!outcomeAdmission.accepted)throw new Error('component validation production invariant failure');return outcomeAdmission.value}
  const entries:ComponentValidationEntryV1[]=[];const diagnostics:ComponentValidationDiagnosticV1[]=[]
  for(const kind of COMPONENT_KIND_ORDER){
   const descriptor=manifest.component_artifacts.find(item=>item.component_kind===kind);const transport=input.component_payloads.find(item=>item.component_kind===kind)
   if(!descriptor||!transport||transport.content_type!=='application/json'||!b64.test(transport.content_base64))return reject(observedAt,`$.component_payloads[component_kind=${kind}].content_base64`)
   const bytes=Uint8Array.from(atob(transport.content_base64),char=>char.charCodeAt(0));if(bytes.length===0)return reject(observedAt,`$.component_payloads[component_kind=${kind}].content_base64`)
   const digest=await hash(bytes);const evidence=[{kind:'content_addressed',content_ref:manifest.context_handoff_manifest_ref} as const,await generateDescriptorEvidenceRefV1(manifest,descriptor),await generateObservedBytesEvidenceRefV1(manifest,kind,bytes.length,digest)]
   let decoded:unknown;let state:ComponentValidationEntryV1['contract_version_state']='unreadable';let observed:string|undefined;let valid=false;let code:ComponentValidationDiagnosticV1['code']='component_schema_invalid';let path=`$.decoded_payloads[component_kind=${kind}]`
   try{decoded=JSON.parse(decoder.decode(bytes));if(typeof decoded==='object'&&decoded!==null&&!Array.isArray(decoded)){const payload=decoded as {contract_version?:unknown;component_kind?:unknown};if(!Object.prototype.hasOwnProperty.call(payload,'contract_version'))state='missing';else if(typeof payload.contract_version!=='string')state='unreadable';else {observed=payload.contract_version;state=observed===EXPECTED_COMPONENT_CONTRACT_VERSIONS[kind]?'matched':'mismatch'};if(state==='matched'&&validators[kind](decoded)&&payload.component_kind===kind)valid=true;else if(payload.component_kind!==kind){code='component_cross_reference_mismatch';path+=`.component_kind`}}}catch{}
   if(descriptor.byte_length!==bytes.length){valid=false;code='component_length_mismatch';path=`$.context_handoff_manifest.component_artifacts[component_kind=${kind}].byte_length`}
   if(descriptor.sha256!==digest||descriptor.component_id!==`${kind}/sha256-${descriptor.sha256}`){valid=false;code='component_digest_mismatch';path=`$.context_handoff_manifest.component_artifacts[component_kind=${kind}].sha256`}
   const diagnosticIds:string[]=[]
   if(!valid){const draft={component_kind:kind,code,path,message:code.replace(/_/g,' '),evidence_refs:evidence};const diagnostic_id=await generateComponentValidationDiagnosticIdV1(draft);diagnostics.push({...draft,diagnostic_id});diagnosticIds.push(diagnostic_id)}
   const entry:ComponentValidationEntryV1=state==='matched'?{component_kind:kind,status:valid?'valid':'invalid',computed_sha256:digest,computed_byte_length:bytes.length,contract_version_state:'matched',observed_contract_version:observed!,diagnostic_ids:diagnosticIds}:state==='mismatch'?{component_kind:kind,status:'invalid',computed_sha256:digest,computed_byte_length:bytes.length,contract_version_state:'mismatch',observed_contract_version:observed!,diagnostic_ids:diagnosticIds}:{component_kind:kind,status:'invalid',computed_sha256:digest,computed_byte_length:bytes.length,contract_version_state:state,diagnostic_ids:diagnosticIds}
   entries.push(entry)
  }
  const result={contract_version:'context-handoff-component-validation-result-v1',result_kind:entries.every(entry=>entry.status==='valid')?'valid':'invalid',result_reason_code:entries.every(entry=>entry.status==='valid')?'all_components_valid':'component_validation_failed',context_handoff_manifest_ref:manifest.context_handoff_manifest_ref,component_results:entries,diagnostics:diagnostics.sort((a,b)=>a.diagnostic_id.localeCompare(b.diagnostic_id)),validator_contract_version:'context-handoff-component-validator-v1',validated_at:observedAt}
  const resultAdmission=validateContextHandoffComponentValidationResultV1(result,observedAt);if(!resultAdmission.accepted)throw new TypeError('canonical result admission failed')
  const candidate={contract_version:'context-handoff-component-validation-production-outcome-v1',outcome_kind:'produced' as const,component_validation_result:resultAdmission.value,validator_contract_version:'context-handoff-component-validator-v1' as const,observed_at:observedAt};const outcomeAdmission=await validateComponentValidationProductionOutcomeV1(candidate,value,observedAt);if(!outcomeAdmission.accepted)throw new Error(JSON.stringify(outcomeAdmission.rejection));return outcomeAdmission.value
 }catch(error){throw error}
}
