/** Pure Step 4 builders. Inputs supply every timestamp and source-derived value. */
import { deepFreezeClone, generateContextHandoffManifestRef, validateContextHandoffManifestV1, verifyContextHandoffManifestRef, verifyContextHealthReference, type CanonicalSourceRefV1, type ComponentArtifactV1, type ContextHandoffManifestV1, type HandoffFactV1, type SourceProvenanceV1 } from '../index'
import { ARTIFACT_GENERATOR_VERSION, BOOTSTRAP_INSTRUCTION_SEQUENCE, BOOTSTRAP_STOP_CONDITIONS, CHECKPOINT_RECORD_BUILDER_RESULT_VERSION, CHECKPOINT_RECORD_VERSION, CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION, type ArtifactBuilderFailureV1, type CanonicalRecordManifestPayloadV1, type CheckpointRecordBuilderInputV1, type CheckpointRecordBuilderResultV1, type CheckpointRecordV1, type CompressedContextHandoffPayloadV1, type ContextBootstrapPromptPayloadV1, type ContextHandoffBundleBuilderInputV1, type ContextHandoffBundleBuilderResultV1, type DecodedComponentPayloadV1, type CompletenessIssueV1, type GeneratedComponentV1, type RedactionRecordV1, type RepositoryStateSnapshotPayloadV1, type ValidationSnapshotPayloadV1, generateCheckpointRecordBuilderInputRef, generateCheckpointRecordBuilderResultRef, generateCheckpointRecordRef, generateContextHandoffBundleBuilderInputRef, generateContextHandoffBundleBuilderResultRef, validateArtifactSafeProjection, validateCheckpointRecordBuilderInputV1, validateCheckpointRecordBuilderResultV1, validateCheckpointRecordSemanticsV1, validateCheckpointRecordV1, validateContextHandoffBundleBuilderInputV1, verifyCheckpointRecordBuilderResultIntegrityV1, verifyCheckpointRecordRef, verifyContextHandoffBundleBuilderResultIntegrityV1 } from './contracts'

const componentKinds=['compressed_context_handoff','bootstrap_prompt','canonical_record_manifest','repository_state_snapshot','validation_snapshot'] as const
const payloadVersions={compressed_context_handoff:'compressed-context-handoff-payload-v1',bootstrap_prompt:'context-bootstrap-prompt-payload-v1',canonical_record_manifest:'canonical-record-manifest-payload-v1',repository_state_snapshot:'repository-state-snapshot-payload-v1',validation_snapshot:'validation-snapshot-payload-v1'} as const
type DynamicObject={readonly [key:string]:unknown}
const dynamic=(v:unknown):DynamicObject|undefined=>typeof v==='object'&&v!==null&&!Array.isArray(v)?v as DynamicObject:undefined
const jcs=(v:unknown):string=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(jcs).join(',')+']';const x=dynamic(v);if(x===undefined)throw new TypeError('canonical bytes require a JSON object');return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+jcs(x[k])).join(',')+'}'}
const digest=async(v:unknown)=>{const bytes=new TextEncoder().encode(jcs(v));const d=await crypto.subtle.digest('SHA-256',bytes);return {bytes,sha:[...new Uint8Array(d)].map(n=>n.toString(16).padStart(2,'0')).join('')}}
const utf8Compare=(left:string,right:string)=>{const a=new TextEncoder().encode(left),b=new TextEncoder().encode(right);for(let index=0;index<Math.min(a.length,b.length);index++){const difference=a[index]-b[index];if(difference!==0)return difference}return a.length-b.length}
const sortFacts=(v:readonly HandoffFactV1[])=>[...v].sort((a,b)=>utf8Compare(a.fact_id,b.fact_id))
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b)
const issue=(code:CompletenessIssueV1['code'],path:string):CompletenessIssueV1=>({issue_id:`${code}/${path.replace(/[^A-Za-z0-9]+/g,'-')}`,code,path,affected_ids:[],evidence_refs:[],decision_owner:'integrated_lead',retry_policy:'after_input_correction'})
const architectFailures:readonly ArtifactBuilderFailureV1['failure_code'][]=['unsupported_contract_version','decision_outcome_unsupported','required_artifact_class_mismatch']
const implementationFailures:readonly ArtifactBuilderFailureV1['failure_code'][]=['component_payload_invalid','component_set_invalid','component_cross_reference_mismatch','component_digest_mismatch','component_length_mismatch','checkpoint_record_projection_invalid','checkpoint_record_semantic_mismatch','builder_result_projection_invalid','normative_reference_generation_failed','builder_internal_failure']
const fail=(failure_code:ArtifactBuilderFailureV1['failure_code'],failure_stage:ArtifactBuilderFailureV1['failure_stage'],path:string,verified_refs:readonly CanonicalSourceRefV1[]=[]):ArtifactBuilderFailureV1=>({failure_code,failure_stage,path,message:failure_code.split('_').join(' '),verified_refs,decision_owner:architectFailures.includes(failure_code)?'backend_architect':implementationFailures.includes(failure_code)?'backend_implementer':'integrated_lead',retry_policy:architectFailures.includes(failure_code)?'after_architect_decision':implementationFailures.includes(failure_code)?'after_implementation_fix':'after_input_correction'})
type CheckpointResultSeed=
 | Omit<Extract<CheckpointRecordBuilderResultV1,{readonly result_kind:'complete'}>,'checkpoint_record_builder_result_ref'>
 | Omit<Extract<CheckpointRecordBuilderResultV1,{readonly result_kind:'incomplete'}>,'checkpoint_record_builder_result_ref'>
 | Omit<Extract<CheckpointRecordBuilderResultV1,{readonly result_kind:'failure'}>,'checkpoint_record_builder_result_ref'>
type BundleResultSeed=
 | Omit<Extract<ContextHandoffBundleBuilderResultV1,{readonly result_kind:'complete'}>,'context_handoff_bundle_builder_result_ref'>
 | Omit<Extract<ContextHandoffBundleBuilderResultV1,{readonly result_kind:'incomplete'}>,'context_handoff_bundle_builder_result_ref'>
 | Omit<Extract<ContextHandoffBundleBuilderResultV1,{readonly result_kind:'failure'}>,'context_handoff_bundle_builder_result_ref'>
async function checkpointResult(value:CheckpointResultSeed):Promise<CheckpointRecordBuilderResultV1>{
 const seed:CheckpointRecordBuilderResultV1=value.result_kind==='complete'
  ?{contract_version:value.contract_version,checkpoint_record_builder_result_ref:'',result_kind:'complete',checkpoint_record_builder_input_ref:value.checkpoint_record_builder_input_ref,checkpoint_record:value.checkpoint_record,publication_performed:false}
  :value.result_kind==='incomplete'
   ?{contract_version:value.contract_version,checkpoint_record_builder_result_ref:'',result_kind:'incomplete',checkpoint_record_builder_input_ref:value.checkpoint_record_builder_input_ref,completeness_issues:value.completeness_issues,publication_performed:false}
   :{contract_version:value.contract_version,checkpoint_record_builder_result_ref:'',result_kind:'failure',failure:value.failure,publication_performed:false}
 const reference=await generateCheckpointRecordBuilderResultRef(seed)
 const result:CheckpointRecordBuilderResultV1=seed.result_kind==='complete'
  ?{...seed,checkpoint_record_builder_result_ref:reference}
  :seed.result_kind==='incomplete'
   ?{...seed,checkpoint_record_builder_result_ref:reference}
   :{...seed,checkpoint_record_builder_result_ref:reference}
 return deepFreezeClone(result)
}
async function bundleResult(value:BundleResultSeed):Promise<ContextHandoffBundleBuilderResultV1>{
 const seed:ContextHandoffBundleBuilderResultV1=value.result_kind==='complete'
  ?{contract_version:value.contract_version,context_handoff_bundle_builder_result_ref:'',result_kind:'complete',context_handoff_bundle_builder_input_ref:value.context_handoff_bundle_builder_input_ref,context_handoff_manifest:value.context_handoff_manifest,generated_components:value.generated_components,publication_performed:false}
  :value.result_kind==='incomplete'
   ?{contract_version:value.contract_version,context_handoff_bundle_builder_result_ref:'',result_kind:'incomplete',context_handoff_bundle_builder_input_ref:value.context_handoff_bundle_builder_input_ref,completeness_issues:value.completeness_issues,publication_performed:false}
   :{contract_version:value.contract_version,context_handoff_bundle_builder_result_ref:'',result_kind:'failure',failure:value.failure,publication_performed:false}
 const reference=await generateContextHandoffBundleBuilderResultRef(seed)
 const result:ContextHandoffBundleBuilderResultV1=seed.result_kind==='complete'
  ?{...seed,context_handoff_bundle_builder_result_ref:reference}
  :seed.result_kind==='incomplete'
   ?{...seed,context_handoff_bundle_builder_result_ref:reference}
   :{...seed,context_handoff_bundle_builder_result_ref:reference}
 return deepFreezeClone(result)
}
async function commonValid(v:CheckpointRecordBuilderInputV1|ContextHandoffBundleBuilderInputV1){return await verifyContextHealthReference(v.context_health_policy)&&await verifyContextHealthReference(v.context_health_evaluation_input)&&await verifyContextHealthReference(v.context_health_decision)&&v.context_health_policy.context_health_policy_ref===v.context_health_evaluation_input.policy_ref&&v.context_health_decision.context_health_policy_ref===v.context_health_policy.context_health_policy_ref&&v.context_health_decision.context_health_input_ref===v.context_health_evaluation_input.context_health_input_ref}
function factIssues(facts:readonly HandoffFactV1[],redactions:readonly RedactionRecordV1[],provenance:readonly SourceProvenanceV1[]):CompletenessIssueV1[]{const ids=new Set(facts.map(x=>x.fact_id));const freshnessIds=new Set(facts.filter(x=>x.fact_kind==='freshness').map(x=>x.fact_id));const p=new Set(provenance.map(x=>x.provenance_id));const r=new Map(redactions.map(x=>[x.redaction_record_id,x]));const out:CompletenessIssueV1[]=[];for(const f of facts){if(f.evidence_state==='unverified')out.push(issue('material_fact_unverified',`$.material_facts.${f.fact_id}`));if(f.evidence_state==='stale')out.push(issue('material_fact_stale',`$.material_facts.${f.fact_id}`));if(f.evidence_state==='redacted')out.push(issue('material_fact_redacted',`$.material_facts.${f.fact_id}`));if(f.provenance_ids.some(x=>!p.has(x)))out.push(issue('material_fact_provenance_missing',`$.material_facts.${f.fact_id}`));if(f.freshness_evidence_ids.some(x=>!freshnessIds.has(x)))out.push(issue('required_component_source_incomplete',`$.material_facts.${f.fact_id}.freshness_evidence_ids`));for(const id of f.redaction_record_ids){const x=r.get(id);if(!x||!x.affected_fact_ids.includes(f.fact_id))out.push(issue('redaction_target_incomplete',`$.material_facts.${f.fact_id}`));if(x?.disposition==='fact_value_removed')out.push(issue('material_fact_redacted',`$.material_facts.${f.fact_id}`))}}for(const record of redactions)for(const affectedFactId of record.affected_fact_ids){const affected=facts.find(fact=>fact.fact_id===affectedFactId);if(!affected||!affected.redaction_record_ids.includes(record.redaction_record_id))out.push(issue('redaction_target_incomplete','$.redaction_records'))}return out}
const hasContradictedProvenance=(facts:readonly HandoffFactV1[],provenance:readonly SourceProvenanceV1[])=>{const contradicted=new Set(provenance.filter(item=>item.verification_state==='contradicted').map(item=>item.provenance_id));return facts.some(fact=>fact.provenance_ids.some(id=>contradicted.has(id)))}
export async function buildCheckpointRecordV1(input:unknown):Promise<CheckpointRecordBuilderResultV1>{
 if(!validateCheckpointRecordBuilderInputV1(input))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('builder_input_invalid','admission','$'),publication_performed:false})
 const value=input
 if(value.checkpoint_record_builder_input_ref!==await generateCheckpointRecordBuilderInputRef(value)||!await commonValid(value))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('content_reference_mismatch','identity','$',[value.context_health_evaluation_input.workflow_identity.canonical_task_record]),publication_performed:false})
 const decision=value.context_health_decision,evaluationInput=value.context_health_evaluation_input
 if(decision.outcome!=='checkpoint_only')return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('decision_outcome_unsupported','identity','$.context_health_decision.outcome'),publication_performed:false})
 if(decision.required_artifact_class!=='checkpoint_record')return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('required_artifact_class_mismatch','identity','$.context_health_decision.required_artifact_class'),publication_performed:false})
 if(hasContradictedProvenance(value.material_facts,value.source_provenance))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('content_reference_mismatch','identity','$.source_provenance'),publication_performed:false})
 const issues=factIssues(value.material_facts,value.redaction_records,value.source_provenance)
 if(issues.length)return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'incomplete',checkpoint_record_builder_input_ref:value.checkpoint_record_builder_input_ref,completeness_issues:issues,publication_performed:false})
 const placeholderRef=`evidence/context-health-checkpoints/sha256-${'0'.repeat(64)}`
 const candidate:CheckpointRecordV1={
  contract_version:CHECKPOINT_RECORD_VERSION,checkpoint_record_ref:placeholderRef,task_id:decision.task_id,assignment_revision:decision.assignment_revision,role:decision.role,repository:decision.repository,workflow_phase:decision.workflow_phase,checkpoint_instance_id:decision.checkpoint_instance_id,checkpoint_type:decision.checkpoint_type,canonical_task_record:evaluationInput.workflow_identity.canonical_task_record,dispatch_record:evaluationInput.workflow_identity.dispatch_record,context_health_policy_ref:decision.context_health_policy_ref,context_health_input_ref:decision.context_health_input_ref,context_health_decision_ref:decision.context_health_decision_ref,checkpoint_rule_ref:decision.checkpoint_rule_ref,protected_action_ref:evaluationInput.checkpoint.protected_action_ref,outcome:'checkpoint_only',legal_action_class:'assigned_work_allowed',required_artifact_class:'checkpoint_record',soft_score:decision.soft_score,applied_atomic_signal_rule_refs:[...decision.applied_atomic_signal_rule_refs],applied_coverage_rule_refs:[...decision.applied_coverage_rule_refs],hard_rule_refs:[],forced_handoff_rule_refs:[],soft_contributions:decision.soft_contributions.map(contribution=>({...contribution,evidence_refs:[...contribution.evidence_refs]})),applied_unknown_handling_rule_refs:[...decision.applied_unknown_handling_rule_refs],unknown_advisory_signal_codes:[...decision.unknown_advisory_signal_codes],prior_decision_refs:[...decision.prior_decision_refs],checkpoint_escalation_evaluation:decision.checkpoint_escalation_evaluation,operator_override_evaluation:decision.operator_override_evaluation,workflow_identity_snapshot:evaluationInput.workflow_identity,constraint_snapshot:evaluationInput.constraint_snapshot,canonical_record_coverage:evaluationInput.canonical_record_coverage,validation_bindings:evaluationInput.validation_bindings,material_facts:sortFacts(value.material_facts),unresolved_items:sortFacts(value.material_facts.filter(fact=>fact.resolution_state==='unresolved')),redaction_records:[...value.redaction_records].sort((left,right)=>utf8Compare(left.redaction_record_id,right.redaction_record_id)),source_provenance:[...value.source_provenance].sort((left,right)=>utf8Compare(left.provenance_id,right.provenance_id)),generator_contract_version:ARTIFACT_GENERATOR_VERSION,generated_at:value.generated_at
 }
 if(!validateCheckpointRecordV1(candidate))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('checkpoint_record_projection_invalid','projection','$'),publication_performed:false})
 const candidateSemantics=validateCheckpointRecordSemanticsV1(candidate,value)
 if(!candidateSemantics.valid)return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('checkpoint_record_semantic_mismatch','projection',candidateSemantics.path),publication_performed:false})
 const checkpointRecordRef=await generateCheckpointRecordRef(candidate)
 const record:CheckpointRecordV1={...candidate,checkpoint_record_ref:checkpointRecordRef}
 if(!validateArtifactSafeProjection(record))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('unsafe_material_unredacted','projection','$'),publication_performed:false})
 if(!validateCheckpointRecordV1(record)||!validateCheckpointRecordSemanticsV1(record,value).valid||!await verifyCheckpointRecordRef(record))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('checkpoint_record_projection_invalid','reference_generation','$'),publication_performed:false})
 const result=await checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'complete',checkpoint_record_builder_input_ref:value.checkpoint_record_builder_input_ref,checkpoint_record:record,publication_performed:false})
 if(!validateCheckpointRecordBuilderResultV1(result)||!await verifyCheckpointRecordBuilderResultIntegrityV1(result,value))return checkpointResult({contract_version:CHECKPOINT_RECORD_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('builder_result_projection_invalid','reference_generation','$'),publication_performed:false})
 return result
}
function categories(v:ContextHandoffBundleBuilderInputV1){const f=v.material_facts;return same(v.completed_work,sortFacts(f.filter(x=>x.fact_kind==='completed_work')))&&same(v.frozen_decisions,sortFacts(f.filter(x=>x.fact_kind==='frozen_decision')))&&same(v.unresolved_items,sortFacts(f.filter(x=>x.resolution_state==='unresolved')))&&same(v.blockers_and_risks,sortFacts(f.filter(x=>x.fact_kind==='blocker'||x.fact_kind==='risk')))&&same(v.forbidden_operations,sortFacts(f.filter(x=>x.fact_kind==='forbidden_operation')))&&same(v.freshness_evidence,sortFacts(f.filter(x=>x.fact_kind==='freshness')))}
export async function buildContextHandoffBundleV1(input:unknown):Promise<ContextHandoffBundleBuilderResultV1>{
 if(!validateContextHandoffBundleBuilderInputV1(input))return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('builder_input_invalid','admission','$'),publication_performed:false})
 const value=input
 if(value.context_handoff_bundle_builder_input_ref!==await generateContextHandoffBundleBuilderInputRef(value)||!await commonValid(value))return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('content_reference_mismatch','identity','$'),publication_performed:false})
 const decision=value.context_health_decision
 if(!['handoff_required','hard_stop_and_handoff'].includes(decision.outcome))return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('decision_outcome_unsupported','identity','$.context_health_decision.outcome'),publication_performed:false})
 if(decision.required_artifact_class!=='context_handoff_manifest')return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('required_artifact_class_mismatch','identity','$.context_health_decision.required_artifact_class'),publication_performed:false})
 if(hasContradictedProvenance(value.material_facts,value.source_provenance))return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('content_reference_mismatch','identity','$.source_provenance'),publication_performed:false})
 if(!categories(value))return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('fact_category_mismatch','completeness_admission','$.material_facts'),publication_performed:false})
 const issues=factIssues(value.material_facts,value.redaction_records,value.source_provenance)
 if(value.repository_state.state==='unavailable')issues.push(issue('repository_state_unavailable','$.repository_state'))
 if(issues.length)return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'incomplete',context_handoff_bundle_builder_input_ref:value.context_handoff_bundle_builder_input_ref,completeness_issues:issues,publication_performed:false})
 const common={context_handoff_bundle_builder_input_ref:value.context_handoff_bundle_builder_input_ref,task_id:decision.task_id,assignment_revision:decision.assignment_revision,role:decision.role,repository:decision.repository,workflow_phase:decision.workflow_phase,checkpoint_instance_id:decision.checkpoint_instance_id,context_health_decision_ref:decision.context_health_decision_ref,generated_at:value.generated_at,generator_contract_version:ARTIFACT_GENERATOR_VERSION}
 const compressed:CompressedContextHandoffPayloadV1={...common,contract_version:payloadVersions.compressed_context_handoff,component_kind:'compressed_context_handoff',canonical_task_record:value.canonical_task_record,workflow_identity_snapshot:value.workflow_identity_snapshot,completed_work:value.completed_work,frozen_decisions:value.frozen_decisions,unresolved_items:value.unresolved_items,blockers_and_risks:value.blockers_and_risks,forbidden_operations:value.forbidden_operations,validation_fact_ids:sortFacts(value.material_facts.filter(fact=>fact.fact_kind==='validation_result')).map(fact=>fact.fact_id),exact_next_action:value.exact_next_action,freshness_evidence:value.freshness_evidence,redaction_records:value.redaction_records,source_provenance:value.source_provenance}
 const bootstrap:ContextBootstrapPromptPayloadV1={...common,contract_version:payloadVersions.bootstrap_prompt,component_kind:'bootstrap_prompt',canonical_task_record:value.canonical_task_record,expected_manifest_contract_version:'context-handoff-manifest-v1',exact_next_action:value.exact_next_action,unresolved_item_ids:value.unresolved_items.map(fact=>fact.fact_id),blocker_fact_ids:value.blockers_and_risks.filter(fact=>fact.fact_kind==='blocker').map(fact=>fact.fact_id),instruction_sequence:[...BOOTSTRAP_INSTRUCTION_SEQUENCE],stop_conditions:[...BOOTSTRAP_STOP_CONDITIONS]}
 const canonicalRecord:CanonicalRecordManifestPayloadV1={...common,contract_version:payloadVersions.canonical_record_manifest,component_kind:'canonical_record_manifest',canonical_task_record:value.canonical_task_record,dispatch_record:value.dispatch_record,policy_ref:decision.context_health_policy_ref,evaluation_input_ref:decision.context_health_input_ref,decision_ref:decision.context_health_decision_ref,fact_source_bindings:sortFacts(value.material_facts).map(fact=>({fact_id:fact.fact_id,source_refs:fact.source_refs,provenance_ids:fact.provenance_ids,freshness_evidence_ids:fact.freshness_evidence_ids,redaction_record_ids:fact.redaction_record_ids})),source_provenance:value.source_provenance,redaction_records:value.redaction_records}
 const repositoryState:RepositoryStateSnapshotPayloadV1=value.repository_state.state==='available'
  ?{...common,contract_version:payloadVersions.repository_state_snapshot,component_kind:'repository_state_snapshot',state:'available',repository:value.repository_state.repository,workflow_identity_snapshot:value.repository_state.workflow_identity_snapshot,dirty_state:value.repository_state.dirty_state,observed_at:value.repository_state.observed_at,evidence_refs:value.repository_state.evidence_refs,canonical_task_record:value.canonical_task_record,dispatch_record:value.dispatch_record}
  :{...common,contract_version:payloadVersions.repository_state_snapshot,component_kind:'repository_state_snapshot',state:'unavailable',repository:value.repository_state.repository,workflow_identity_snapshot:value.repository_state.workflow_identity_snapshot,observed_at:value.repository_state.observed_at,attempt:value.repository_state.attempt,canonical_task_record:value.canonical_task_record,dispatch_record:value.dispatch_record}
 const warningFactIds=[...new Set(value.validation_annotations.filter(annotation=>annotation.annotation_kind==='warning').map(annotation=>annotation.fact_id))].sort(utf8Compare)
 const unverifiedValidationIds=[...new Set([...value.context_health_evaluation_input.validation_bindings.filter(binding=>binding.state==='not_started'||binding.state==='running'||binding.state==='unavailable').map(binding=>binding.validation_id),...value.validation_annotations.filter(annotation=>annotation.annotation_kind==='unverified_item').map(annotation=>annotation.validation_id)])].sort(utf8Compare)
 const validationPayload:ValidationSnapshotPayloadV1={...common,contract_version:payloadVersions.validation_snapshot,component_kind:'validation_snapshot',required_validation_refs:value.context_health_evaluation_input.constraint_snapshot.required_validation_refs,validation_bindings:value.context_health_evaluation_input.validation_bindings,validation_facts:sortFacts(value.material_facts.filter(fact=>fact.fact_kind==='validation_result')),warning_fact_ids:warningFactIds,unverified_validation_ids:unverifiedValidationIds}
 const payloads:Record<ComponentArtifactV1['component_kind'],DecodedComponentPayloadV1>={compressed_context_handoff:compressed,bootstrap_prompt:bootstrap,canonical_record_manifest:canonicalRecord,repository_state_snapshot:repositoryState,validation_snapshot:validationPayload}
 const generated:GeneratedComponentV1[]=[]
 for(const componentKind of componentKinds){
  const payload=payloads[componentKind]
  if(!validateArtifactSafeProjection(payload))return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('unsafe_material_unredacted','projection',`$.${componentKind}`),publication_performed:false})
  const payloadDigest=await digest(payload)
  const artifact:ComponentArtifactV1={component_id:`${componentKind}/sha256-${payloadDigest.sha}`,component_kind:componentKind,content_type:'application/json',byte_length:payloadDigest.bytes.length,sha256:payloadDigest.sha}
  generated.push({artifact,payload,transport:{component_kind:componentKind,content_type:'application/json',content_base64:btoa(String.fromCharCode(...payloadDigest.bytes))}})
 }
 const validationArtifact=generated[4].artifact
 const manifestCandidate:ContextHandoffManifestV1={contract_version:'context-handoff-manifest-v1',context_handoff_manifest_ref:`evidence/context-handoffs/sha256-${'0'.repeat(64)}`,task_id:decision.task_id,assignment_revision:decision.assignment_revision,role:decision.role,repository:decision.repository,workflow_phase:decision.workflow_phase,checkpoint_instance_id:decision.checkpoint_instance_id,context_health_decision_ref:decision.context_health_decision_ref,canonical_task_record:value.canonical_task_record,dispatch_record:value.dispatch_record,workflow_identity_snapshot:value.workflow_identity_snapshot,completed_work:value.completed_work,frozen_decisions:value.frozen_decisions,unresolved_items:value.unresolved_items,blockers_and_risks:value.blockers_and_risks,forbidden_operations:value.forbidden_operations,validation_snapshot:{component_id:validationArtifact.component_id,component_kind:'validation_snapshot',sha256:validationArtifact.sha256},exact_next_action:value.exact_next_action,component_artifacts:generated.map(component=>component.artifact),material_facts:sortFacts(value.material_facts),freshness_evidence:value.freshness_evidence,redaction_records:sortFacts(value.material_facts.filter(fact=>fact.fact_kind==='redaction')),source_provenance:value.source_provenance,generator_contract_version:'context-handoff-generator-v1',generated_at:value.generated_at}
 const manifestCandidateAdmission=validateContextHandoffManifestV1(manifestCandidate,value.generated_at)
 if(!manifestCandidateAdmission.accepted)return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('component_cross_reference_mismatch','component_generation','$.context_handoff_manifest'),publication_performed:false})
 const contextHandoffManifestRef=await generateContextHandoffManifestRef(manifestCandidateAdmission.value)
 const manifest:ContextHandoffManifestV1={...manifestCandidateAdmission.value,context_handoff_manifest_ref:contextHandoffManifestRef}
 const manifestAdmission=validateContextHandoffManifestV1(manifest,value.generated_at)
 if(!manifestAdmission.accepted)return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('component_cross_reference_mismatch','component_generation','$.context_handoff_manifest'),publication_performed:false})
 const manifestVerification=await verifyContextHandoffManifestRef(manifestAdmission.value,value.generated_at)
 if(manifestVerification.result_kind!=='matched')return bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail(manifestVerification.result_kind==='internal_failure'?'normative_reference_generation_failed':'content_reference_mismatch','reference_generation','$.context_handoff_manifest.context_handoff_manifest_ref'),publication_performed:false})
 const result=await bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'complete',context_handoff_bundle_builder_input_ref:value.context_handoff_bundle_builder_input_ref,context_handoff_manifest:manifest,generated_components:generated,publication_performed:false})
 return await verifyContextHandoffBundleBuilderResultIntegrityV1(result)?result:bundleResult({contract_version:CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION,result_kind:'failure',failure:fail('component_cross_reference_mismatch','component_generation','$.generated_components'),publication_performed:false})
}
