/** Pure Step 2 artifact contracts. No I/O, clock, environment, or publication. */
import { deepFreezeClone, validateCanonicalSourceRefV1, type CanonicalSourceRefV1, type ComponentArtifactV1, type ContextHandoffManifestV1, type ContextHealthDecisionV1, type ContextHealthEvaluationInputV1, type ContextHealthPolicyV1, type DeepReadonly, type ExactNextActionV1, type HandoffFactV1, type RoleV1, type SourceProvenanceV1, type ValidationBindingV1, type WorkflowIdentityV1 } from '../index'

export const CHECKPOINT_RECORD_VERSION='context-health-checkpoint-record-v1' as const
export const CHECKPOINT_RECORD_BUILDER_INPUT_VERSION='checkpoint-record-builder-input-v1' as const
export const CHECKPOINT_RECORD_BUILDER_RESULT_VERSION='checkpoint-record-builder-result-v1' as const
export const CONTEXT_HANDOFF_BUNDLE_BUILDER_INPUT_VERSION='context-handoff-bundle-builder-input-v1' as const
export const CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION='context-handoff-bundle-builder-result-v1' as const
export const ARTIFACT_GENERATOR_VERSION='context-handoff-artifact-generator-v1' as const
export const REDACTION_CODES=['secret','credential','token','private_endpoint','environment_value','personal_absolute_path','raw_transcript','raw_prompt','raw_source_content','raw_exception','internal_reasoning'] as const
export type RedactionCodeV1=typeof REDACTION_CODES[number]
export const COMPLETENESS_ISSUE_CODES=['required_fact_missing','required_category_projection_incomplete','material_fact_unverified','material_fact_stale','material_fact_redacted','material_fact_provenance_missing','unresolved_state_not_preserved','redaction_target_incomplete','repository_state_unavailable','required_validation_state_unavailable','exact_next_action_unverified','required_component_source_incomplete'] as const
export const ARTIFACT_BUILDER_FAILURE_CODES=['builder_input_invalid','unsupported_contract_version','content_reference_mismatch','policy_input_decision_mismatch','task_identity_mismatch','workflow_identity_mismatch','checkpoint_identity_mismatch','decision_outcome_unsupported','required_artifact_class_mismatch','duplicate_identity','fact_category_mismatch','redaction_record_invalid','unsafe_material_unredacted','component_payload_invalid','component_set_invalid','component_cross_reference_mismatch','component_digest_mismatch','component_length_mismatch','normative_reference_generation_failed','builder_internal_failure'] as const
export const BOOTSTRAP_INSTRUCTION_SEQUENCE=['load_manifest','validate_bundle','fresh_fetch_mutable_state','classify_drift','preserve_unresolved_items','reevaluate_context_health','identify_legal_next_action','stop_on_non_success'] as const
export const BOOTSTRAP_STOP_CONDITIONS=['manifest_invalid','component_invalid','fresh_fetch_unavailable','material_drift','unresolved_owner_unavailable','context_health_non_success'] as const
export interface RedactionRecordV1 { readonly redaction_record_id:string;readonly redaction_code:RedactionCodeV1;readonly affected_fact_ids:readonly string[];readonly source_refs:readonly CanonicalSourceRefV1[];readonly basis_ref:CanonicalSourceRefV1;readonly disposition:'source_detail_omitted'|'fact_value_removed' }
export interface CheckpointRecordV1 { readonly contract_version:typeof CHECKPOINT_RECORD_VERSION;readonly checkpoint_record_ref:string;readonly task_id:string;readonly assignment_revision:number;readonly role:RoleV1;readonly repository:'whatrune/sd-prompt-studio';readonly workflow_phase:string;readonly checkpoint_instance_id:string;readonly checkpoint_type:string;readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1;readonly context_health_policy_ref:string;readonly context_health_input_ref:string;readonly context_health_decision_ref:string;readonly checkpoint_rule_ref:string;readonly protected_action_ref:CanonicalSourceRefV1;readonly outcome:'checkpoint_only';readonly legal_action_class:'assigned_work_allowed';readonly required_artifact_class:'checkpoint_record';readonly soft_score:number;readonly material_facts:readonly HandoffFactV1[];readonly unresolved_items:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION;readonly generated_at:string }
export interface CheckpointRecordBuilderInputV1 { readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_INPUT_VERSION;readonly checkpoint_record_builder_input_ref:string;readonly context_health_policy:ContextHealthPolicyV1;readonly context_health_evaluation_input:ContextHealthEvaluationInputV1;readonly context_health_decision:ContextHealthDecisionV1;readonly material_facts:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly generated_at:string;readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION }
export type RepositoryStateInputV1={readonly state:'available';readonly repository:'whatrune/sd-prompt-studio';readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly dirty_state:'clean'|'dirty';readonly observed_at:string;readonly evidence_refs:readonly CanonicalSourceRefV1[]}|{readonly state:'unavailable';readonly repository:'whatrune/sd-prompt-studio';readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly observed_at:string;readonly attempt:{readonly attempt_id:string}}
export interface ValidationAnnotationV1 {readonly annotation_id:string;readonly validation_id:string;readonly annotation_kind:'warning'|'unverified_item';readonly fact_id:string;readonly source_refs:readonly CanonicalSourceRefV1[]}
export interface ContextHandoffBundleBuilderInputV1 { readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_INPUT_VERSION;readonly context_handoff_bundle_builder_input_ref:string;readonly context_health_policy:ContextHealthPolicyV1;readonly context_health_evaluation_input:ContextHealthEvaluationInputV1;readonly context_health_decision:ContextHealthDecisionV1;readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1;readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly completed_work:readonly HandoffFactV1[];readonly frozen_decisions:readonly HandoffFactV1[];readonly unresolved_items:readonly HandoffFactV1[];readonly blockers_and_risks:readonly HandoffFactV1[];readonly forbidden_operations:readonly HandoffFactV1[];readonly exact_next_action:ExactNextActionV1;readonly validation_annotations:readonly ValidationAnnotationV1[];readonly material_facts:readonly HandoffFactV1[];readonly freshness_evidence:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly repository_state:RepositoryStateInputV1;readonly generated_at:string;readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION }
export interface CompletenessIssueV1 { readonly issue_id:string;readonly code:typeof COMPLETENESS_ISSUE_CODES[number];readonly path:string;readonly affected_ids:readonly string[];readonly evidence_refs:readonly CanonicalSourceRefV1[];readonly decision_owner:'integrated_lead';readonly retry_policy:'after_input_correction' }
export interface ArtifactBuilderFailureV1 { readonly failure_code:typeof ARTIFACT_BUILDER_FAILURE_CODES[number];readonly failure_stage:'admission'|'identity'|'completeness_admission'|'projection'|'component_generation'|'reference_generation'|'internal';readonly path:string;readonly message:string;readonly verified_refs:readonly CanonicalSourceRefV1[];readonly decision_owner:RoleV1;readonly retry_policy:'after_input_correction'|'after_architect_decision'|'after_implementation_fix' }
export type CheckpointRecordBuilderResultV1={readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_RESULT_VERSION;readonly checkpoint_record_builder_result_ref:string;readonly result_kind:'complete';readonly checkpoint_record_builder_input_ref:string;readonly checkpoint_record:CheckpointRecordV1;readonly publication_performed:false}|{readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_RESULT_VERSION;readonly checkpoint_record_builder_result_ref:string;readonly result_kind:'incomplete';readonly checkpoint_record_builder_input_ref:string;readonly completeness_issues:readonly CompletenessIssueV1[];readonly publication_performed:false}|{readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_RESULT_VERSION;readonly checkpoint_record_builder_result_ref:string;readonly result_kind:'failure';readonly failure:ArtifactBuilderFailureV1;readonly publication_performed:false}
export type ContextHandoffBundleBuilderResultV1={readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION;readonly context_handoff_bundle_builder_result_ref:string;readonly result_kind:'complete';readonly context_handoff_bundle_builder_input_ref:string;readonly context_handoff_manifest:ContextHandoffManifestV1;readonly generated_components:readonly GeneratedComponentV1[];readonly publication_performed:false}|{readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION;readonly context_handoff_bundle_builder_result_ref:string;readonly result_kind:'incomplete';readonly context_handoff_bundle_builder_input_ref:string;readonly completeness_issues:readonly CompletenessIssueV1[];readonly publication_performed:false}|{readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION;readonly context_handoff_bundle_builder_result_ref:string;readonly result_kind:'failure';readonly failure:ArtifactBuilderFailureV1;readonly publication_performed:false}
export interface ComponentPayloadBaseV1 {readonly context_handoff_bundle_builder_input_ref:string;readonly task_id:string;readonly assignment_revision:number;readonly role:RoleV1;readonly repository:'whatrune/sd-prompt-studio';readonly workflow_phase:string;readonly checkpoint_instance_id:string;readonly context_health_decision_ref:string;readonly generated_at:string;readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION}
export interface CompressedContextHandoffPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'compressed-context-handoff-payload-v1';readonly component_kind:'compressed_context_handoff';readonly canonical_task_record:CanonicalSourceRefV1;readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly completed_work:readonly HandoffFactV1[];readonly frozen_decisions:readonly HandoffFactV1[];readonly unresolved_items:readonly HandoffFactV1[];readonly blockers_and_risks:readonly HandoffFactV1[];readonly forbidden_operations:readonly HandoffFactV1[];readonly validation_fact_ids:readonly string[];readonly exact_next_action:ExactNextActionV1;readonly freshness_evidence:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[]}
export interface ContextBootstrapPromptPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'context-bootstrap-prompt-payload-v1';readonly component_kind:'bootstrap_prompt';readonly canonical_task_record:CanonicalSourceRefV1;readonly expected_manifest_contract_version:'context-handoff-manifest-v1';readonly exact_next_action:ExactNextActionV1;readonly unresolved_item_ids:readonly string[];readonly blocker_fact_ids:readonly string[];readonly instruction_sequence:readonly string[];readonly stop_conditions:readonly string[]}
export interface CanonicalRecordManifestPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'canonical-record-manifest-payload-v1';readonly component_kind:'canonical_record_manifest';readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1;readonly policy_ref:string;readonly evaluation_input_ref:string;readonly decision_ref:string;readonly fact_source_bindings:readonly FactSourceBindingV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly redaction_records:readonly RedactionRecordV1[]}
export interface FactSourceBindingV1 {readonly fact_id:string;readonly source_refs:readonly CanonicalSourceRefV1[];readonly provenance_ids:readonly string[];readonly freshness_evidence_ids:readonly string[];readonly redaction_record_ids:readonly string[]}
export type RepositoryStateSnapshotPayloadV1=ComponentPayloadBaseV1&RepositoryStateInputV1&{readonly contract_version:'repository-state-snapshot-payload-v1';readonly component_kind:'repository_state_snapshot';readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1}
export interface ValidationSnapshotPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'validation-snapshot-payload-v1';readonly component_kind:'validation_snapshot';readonly required_validation_refs:readonly CanonicalSourceRefV1[];readonly validation_bindings:readonly ValidationBindingV1[];readonly validation_facts:readonly HandoffFactV1[];readonly warning_fact_ids:readonly string[];readonly unverified_validation_ids:readonly string[]}
export type DecodedComponentPayloadV1=CompressedContextHandoffPayloadV1|ContextBootstrapPromptPayloadV1|CanonicalRecordManifestPayloadV1|RepositoryStateSnapshotPayloadV1|ValidationSnapshotPayloadV1
export interface GeneratedComponentV1 { readonly artifact:ComponentArtifactV1;readonly payload:DecodedComponentPayloadV1;readonly transport:{readonly component_kind:ComponentArtifactV1['component_kind'];readonly content_type:'application/json';readonly content_base64:string} }
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const exact=(v:unknown,keys:readonly string[])=>isRecord(v)&&Object.keys(v).length===keys.length&&keys.every(k=>k in v)
const safe=(s:string)=>!/(?:\b(?:secret|credential|token|password|authorization|stack)\b|[A-Za-z]:\\Users\\|https?:\/\/[^\s]+@)/i.test(s)
function canonical(v:unknown):string{if(v===null||typeof v==='boolean'||typeof v==='number'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(!isRecord(v))throw new TypeError('unsupported projection');return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
async function hash(v:unknown,self:string,prefix:string){const x={...(v as Record<string,unknown>)};delete x[self];const bytes=new TextEncoder().encode(canonical(x));const d=await crypto.subtle.digest('SHA-256',bytes);return prefix+[...new Uint8Array(d)].map(n=>n.toString(16).padStart(2,'0')).join('')}
export const generateCheckpointRecordBuilderInputRef=(v:CheckpointRecordBuilderInputV1)=>hash(v,'checkpoint_record_builder_input_ref','evidence/context-health-checkpoint-builder-inputs/sha256-')
export const generateCheckpointRecordRef=(v:CheckpointRecordV1)=>hash(v,'checkpoint_record_ref','evidence/context-health-checkpoints/sha256-')
export const generateCheckpointRecordBuilderResultRef=(v:CheckpointRecordBuilderResultV1)=>hash(v,'checkpoint_record_builder_result_ref','evidence/context-health-checkpoint-builder-results/sha256-')
export const generateContextHandoffBundleBuilderInputRef=(v:ContextHandoffBundleBuilderInputV1)=>hash(v,'context_handoff_bundle_builder_input_ref','evidence/context-handoff-builder-inputs/sha256-')
export const generateContextHandoffBundleBuilderResultRef=(v:ContextHandoffBundleBuilderResultV1)=>hash(v,'context_handoff_bundle_builder_result_ref','evidence/context-handoff-builder-results/sha256-')
export async function verifyCheckpointRecordRef(v:CheckpointRecordV1){return v.checkpoint_record_ref===await generateCheckpointRecordRef(v)}
export function validateRedactionRecordV1(v:unknown):v is RedactionRecordV1{if(!exact(v,['redaction_record_id','redaction_code','affected_fact_ids','source_refs','basis_ref','disposition']))return false;const x=v as Record<string,unknown>;return typeof x.redaction_record_id==='string'&&REDACTION_CODES.includes(x.redaction_code as RedactionCodeV1)&&Array.isArray(x.affected_fact_ids)&&x.affected_fact_ids.length>0&&x.affected_fact_ids.every((y:unknown)=>typeof y==='string')&&Array.isArray(x.source_refs)&&x.source_refs.length>0&&x.source_refs.every(validateCanonicalSourceRefV1)&&validateCanonicalSourceRefV1(x.basis_ref)&&['source_detail_omitted','fact_value_removed'].includes(x.disposition as string)}
export function validateCheckpointRecordBuilderInputV1(v:unknown):v is CheckpointRecordBuilderInputV1{return isRecord(v)&&v.contract_version===CHECKPOINT_RECORD_BUILDER_INPUT_VERSION&&typeof v.checkpoint_record_builder_input_ref==='string'&&v.generator_contract_version===ARTIFACT_GENERATOR_VERSION&&Array.isArray(v.material_facts)&&Array.isArray(v.redaction_records)&&v.redaction_records.every(validateRedactionRecordV1)&&typeof v.generated_at==='string'}
export function validateContextHandoffBundleBuilderInputV1(v:unknown):v is ContextHandoffBundleBuilderInputV1{return isRecord(v)&&v.contract_version===CONTEXT_HANDOFF_BUNDLE_BUILDER_INPUT_VERSION&&typeof v.context_handoff_bundle_builder_input_ref==='string'&&v.generator_contract_version===ARTIFACT_GENERATOR_VERSION&&Array.isArray(v.material_facts)&&Array.isArray(v.redaction_records)&&v.redaction_records.every(validateRedactionRecordV1)&&typeof v.generated_at==='string'}
export function validateCheckpointRecordV1(v:unknown):v is CheckpointRecordV1{return isRecord(v)&&v.contract_version===CHECKPOINT_RECORD_VERSION&&typeof v.checkpoint_record_ref==='string'&&v.outcome==='checkpoint_only'&&v.required_artifact_class==='checkpoint_record'&&validateCanonicalSourceRefV1(v.canonical_task_record)&&validateCanonicalSourceRefV1(v.dispatch_record)&&validateCanonicalSourceRefV1(v.protected_action_ref)}
export function validateCompletenessIssueV1(v:unknown):v is CompletenessIssueV1{return exact(v,['issue_id','code','path','affected_ids','evidence_refs','decision_owner','retry_policy'])&&typeof (v as any).issue_id==='string'&&COMPLETENESS_ISSUE_CODES.includes((v as any).code)&&Array.isArray((v as any).affected_ids)&&new Set((v as any).affected_ids).size===(v as any).affected_ids.length&&Array.isArray((v as any).evidence_refs)&&new Set((v as any).evidence_refs.map(JSON.stringify)).size===(v as any).evidence_refs.length&&(v as any).decision_owner==='integrated_lead'&&(v as any).retry_policy==='after_input_correction'}
export function validateArtifactBuilderFailureV1(v:unknown):v is ArtifactBuilderFailureV1{return exact(v,['failure_code','failure_stage','path','message','verified_refs','decision_owner','retry_policy'])&&ARTIFACT_BUILDER_FAILURE_CODES.includes((v as any).failure_code)&&['admission','identity','completeness_admission','projection','component_generation','reference_generation','internal'].includes((v as any).failure_stage)&&Array.isArray((v as any).verified_refs)&&typeof (v as any).path==='string'&&typeof (v as any).message==='string'}
export function validateCheckpointRecordBuilderResultV1(v:unknown):v is CheckpointRecordBuilderResultV1{if(!isRecord(v)||v.contract_version!==CHECKPOINT_RECORD_BUILDER_RESULT_VERSION||(v as any).publication_performed!==false)return false;const k=(v as any).result_kind;return k==='complete'?exact(v,['contract_version','checkpoint_record_builder_result_ref','result_kind','checkpoint_record_builder_input_ref','checkpoint_record','publication_performed'])&&validateCheckpointRecordV1((v as any).checkpoint_record):k==='incomplete'?exact(v,['contract_version','checkpoint_record_builder_result_ref','result_kind','checkpoint_record_builder_input_ref','completeness_issues','publication_performed'])&&Array.isArray((v as any).completeness_issues)&&(v as any).completeness_issues.length>0&&(v as any).completeness_issues.every(validateCompletenessIssueV1):k==='failure'?exact(v,['contract_version','checkpoint_record_builder_result_ref','result_kind','failure','publication_performed'])&&validateArtifactBuilderFailureV1((v as any).failure):false}
export function validateArtifactSafeProjection(v:unknown):boolean{return safe(canonical(v))}
export function freeze<T>(v:T):DeepReadonly<T>{return deepFreezeClone(v)}
