/** Pure Step 2 artifact contracts. No I/O, clock, environment, or publication. */
import { deepFreezeClone, validateCanonicalSourceRefV1, validateContextHealthDecisionV1, validateContextHealthEvaluationInputV1, validateContextHealthPolicyV1, validateContextHandoffManifestV1, type CanonicalSourceRefV1, type ComponentArtifactV1, type ContextHandoffManifestV1, type ContextHealthDecisionV1, type ContextHealthEvaluationInputV1, type ContextHealthPolicyV1, type DeepReadonly, type ExactNextActionV1, type HandoffFactV1, type RoleV1, type SourceProvenanceV1, type ValidationBindingV1, type WorkflowIdentityV1 } from '../index'

export const CHECKPOINT_RECORD_VERSION='context-health-checkpoint-record-v1' as const
export const CHECKPOINT_RECORD_BUILDER_INPUT_VERSION='checkpoint-record-builder-input-v1' as const
export const CHECKPOINT_RECORD_BUILDER_RESULT_VERSION='checkpoint-record-builder-result-v1' as const
export const CONTEXT_HANDOFF_BUNDLE_BUILDER_INPUT_VERSION='context-handoff-bundle-builder-input-v1' as const
export const CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION='context-handoff-bundle-builder-result-v1' as const
export const ARTIFACT_GENERATOR_VERSION='context-handoff-artifact-generator-v1' as const
export const REDACTION_CODES=['secret','credential','token','private_endpoint','environment_value','personal_absolute_path','raw_transcript','raw_prompt','raw_source_content','raw_exception','internal_reasoning'] as const
export type RedactionCodeV1=typeof REDACTION_CODES[number]
export const COMPLETENESS_ISSUE_CODES=['required_fact_missing','required_category_projection_incomplete','material_fact_unverified','material_fact_stale','material_fact_redacted','material_fact_provenance_missing','unresolved_state_not_preserved','redaction_target_incomplete','repository_state_unavailable','required_validation_state_unavailable','exact_next_action_unverified','required_component_source_incomplete'] as const
export const ARTIFACT_BUILDER_FAILURE_CODES=['builder_input_invalid','unsupported_contract_version','content_reference_mismatch','policy_input_decision_mismatch','task_identity_mismatch','workflow_identity_mismatch','checkpoint_identity_mismatch','decision_outcome_unsupported','required_artifact_class_mismatch','duplicate_identity','fact_category_mismatch','redaction_record_invalid','unsafe_material_unredacted','component_payload_invalid','component_set_invalid','component_cross_reference_mismatch','component_digest_mismatch','component_length_mismatch','normative_reference_generation_failed','builder_internal_failure'] as const
export const BOOTSTRAP_INSTRUCTION_SEQUENCE=['load_manifest','validate_bundle','fresh_fetch_mutable_state','classify_drift','preserve_unresolved_items','reevaluate_context_health','identify_legal_next_action','stop_on_non_success'] as const
export const BOOTSTRAP_STOP_CONDITIONS=['manifest_invalid','component_invalid','fresh_fetch_unavailable','material_drift','unresolved_owner_unavailable','context_health_non_success'] as const
export interface RedactionRecordV1 { readonly redaction_record_id:string;readonly redaction_code:RedactionCodeV1;readonly affected_fact_ids:readonly string[];readonly source_refs:readonly CanonicalSourceRefV1[];readonly basis_ref:CanonicalSourceRefV1;readonly disposition:'source_detail_omitted'|'fact_value_removed' }
export interface CheckpointRecordV1 { readonly contract_version:typeof CHECKPOINT_RECORD_VERSION;readonly checkpoint_record_ref:string;readonly task_id:string;readonly assignment_revision:number;readonly role:RoleV1;readonly repository:'whatrune/sd-prompt-studio';readonly workflow_phase:string;readonly checkpoint_instance_id:string;readonly checkpoint_type:string;readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1;readonly context_health_policy_ref:string;readonly context_health_input_ref:string;readonly context_health_decision_ref:string;readonly checkpoint_rule_ref:string;readonly protected_action_ref:CanonicalSourceRefV1;readonly outcome:'checkpoint_only';readonly legal_action_class:'assigned_work_allowed';readonly required_artifact_class:'checkpoint_record';readonly soft_score:number;readonly material_facts:readonly HandoffFactV1[];readonly unresolved_items:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION;readonly generated_at:string }
export interface CheckpointRecordBuilderInputV1 { readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_INPUT_VERSION;readonly checkpoint_record_builder_input_ref:string;readonly context_health_policy:ContextHealthPolicyV1;readonly context_health_evaluation_input:ContextHealthEvaluationInputV1;readonly context_health_decision:ContextHealthDecisionV1;readonly material_facts:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly generated_at:string;readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION }
export type RepositoryStateInputV1={readonly state:'available';readonly repository:'whatrune/sd-prompt-studio';readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly dirty_state:'clean'|'dirty';readonly observed_at:string;readonly evidence_refs:readonly CanonicalSourceRefV1[]}|{readonly state:'unavailable';readonly repository:'whatrune/sd-prompt-studio';readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly observed_at:string;readonly attempt:{readonly attempt_id:string}}
export interface ValidationAnnotationV1 {readonly annotation_id:string;readonly validation_id:string;readonly annotation_kind:'warning'|'unverified_item';readonly fact_id:string;readonly source_refs:readonly CanonicalSourceRefV1[]}
export interface ContextHandoffBundleBuilderInputV1 { readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_INPUT_VERSION;readonly context_handoff_bundle_builder_input_ref:string;readonly context_health_policy:ContextHealthPolicyV1;readonly context_health_evaluation_input:ContextHealthEvaluationInputV1;readonly context_health_decision:ContextHealthDecisionV1;readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1;readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly completed_work:readonly HandoffFactV1[];readonly frozen_decisions:readonly HandoffFactV1[];readonly unresolved_items:readonly HandoffFactV1[];readonly blockers_and_risks:readonly HandoffFactV1[];readonly forbidden_operations:readonly HandoffFactV1[];readonly exact_next_action:ExactNextActionV1;readonly validation_annotations:readonly ValidationAnnotationV1[];readonly material_facts:readonly HandoffFactV1[];readonly freshness_evidence:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly repository_state:RepositoryStateInputV1;readonly generated_at:string;readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION }
export interface CompletenessIssueV1 { readonly issue_id:string;readonly code:typeof COMPLETENESS_ISSUE_CODES[number];readonly path:string;readonly affected_ids:readonly string[];readonly evidence_refs:readonly CanonicalSourceRefV1[];readonly decision_owner:'integrated_lead';readonly retry_policy:'after_input_correction' }
export interface ArtifactBuilderFailureV1 { readonly failure_code:typeof ARTIFACT_BUILDER_FAILURE_CODES[number];readonly failure_stage:'admission'|'identity'|'completeness_admission'|'projection'|'component_generation'|'reference_generation'|'internal';readonly path:string;readonly message:string;readonly verified_refs:readonly CanonicalSourceRefV1[];readonly decision_owner:RoleV1;readonly retry_policy:'after_input_correction'|'after_architect_decision'|'after_implementation_fix' }
export type CheckpointRecordBuilderResultV1={readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_RESULT_VERSION;readonly checkpoint_record_builder_result_ref:string;readonly result_kind:'complete';readonly checkpoint_record_builder_input_ref:string;readonly checkpoint_record:CheckpointRecordV1;readonly publication_performed:false}|{readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_RESULT_VERSION;readonly checkpoint_record_builder_result_ref:string;readonly result_kind:'incomplete';readonly checkpoint_record_builder_input_ref:string;readonly completeness_issues:readonly CompletenessIssueV1[];readonly publication_performed:false}|{readonly contract_version:typeof CHECKPOINT_RECORD_BUILDER_RESULT_VERSION;readonly checkpoint_record_builder_result_ref:string;readonly result_kind:'failure';readonly failure:ArtifactBuilderFailureV1;readonly publication_performed:false}
export type ContextHandoffBundleBuilderResultV1={readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION;readonly context_handoff_bundle_builder_result_ref:string;readonly result_kind:'complete';readonly context_handoff_bundle_builder_input_ref:string;readonly context_handoff_manifest:ContextHandoffManifestV1;readonly generated_components:readonly GeneratedComponentV1[];readonly publication_performed:false}|{readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION;readonly context_handoff_bundle_builder_result_ref:string;readonly result_kind:'incomplete';readonly context_handoff_bundle_builder_input_ref:string;readonly completeness_issues:readonly CompletenessIssueV1[];readonly publication_performed:false}|{readonly contract_version:typeof CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION;readonly context_handoff_bundle_builder_result_ref:string;readonly result_kind:'failure';readonly failure:ArtifactBuilderFailureV1;readonly publication_performed:false}
export interface ComponentPayloadBaseV1 {readonly context_handoff_bundle_builder_input_ref:string;readonly task_id:string;readonly assignment_revision:number;readonly role:RoleV1;readonly repository:'whatrune/sd-prompt-studio';readonly workflow_phase:string;readonly checkpoint_instance_id:string;readonly context_health_decision_ref:string;readonly generated_at:string;readonly generator_contract_version:typeof ARTIFACT_GENERATOR_VERSION}
export interface CompressedContextHandoffPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'compressed-context-handoff-payload-v1';readonly component_kind:'compressed_context_handoff';readonly canonical_task_record:CanonicalSourceRefV1;readonly workflow_identity_snapshot:WorkflowIdentityV1;readonly completed_work:readonly HandoffFactV1[];readonly frozen_decisions:readonly HandoffFactV1[];readonly unresolved_items:readonly HandoffFactV1[];readonly blockers_and_risks:readonly HandoffFactV1[];readonly forbidden_operations:readonly HandoffFactV1[];readonly validation_fact_ids:readonly string[];readonly exact_next_action:ExactNextActionV1;readonly freshness_evidence:readonly HandoffFactV1[];readonly redaction_records:readonly RedactionRecordV1[];readonly source_provenance:readonly SourceProvenanceV1[]}
export type BootstrapInstructionV1=typeof BOOTSTRAP_INSTRUCTION_SEQUENCE[number]
export type BootstrapStopConditionV1=typeof BOOTSTRAP_STOP_CONDITIONS[number]
export interface ContextBootstrapPromptPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'context-bootstrap-prompt-payload-v1';readonly component_kind:'bootstrap_prompt';readonly canonical_task_record:CanonicalSourceRefV1;readonly expected_manifest_contract_version:'context-handoff-manifest-v1';readonly exact_next_action:ExactNextActionV1;readonly unresolved_item_ids:readonly string[];readonly blocker_fact_ids:readonly string[];readonly instruction_sequence:readonly ['load_manifest','validate_bundle','fresh_fetch_mutable_state','classify_drift','preserve_unresolved_items','reevaluate_context_health','identify_legal_next_action','stop_on_non_success'];readonly stop_conditions:readonly BootstrapStopConditionV1[]}
export interface CanonicalRecordManifestPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'canonical-record-manifest-payload-v1';readonly component_kind:'canonical_record_manifest';readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1;readonly policy_ref:string;readonly evaluation_input_ref:string;readonly decision_ref:string;readonly fact_source_bindings:readonly FactSourceBindingV1[];readonly source_provenance:readonly SourceProvenanceV1[];readonly redaction_records:readonly RedactionRecordV1[]}
export interface FactSourceBindingV1 {readonly fact_id:string;readonly source_refs:readonly CanonicalSourceRefV1[];readonly provenance_ids:readonly string[];readonly freshness_evidence_ids:readonly string[];readonly redaction_record_ids:readonly string[]}
export type RepositoryStateSnapshotPayloadV1=ComponentPayloadBaseV1&RepositoryStateInputV1&{readonly contract_version:'repository-state-snapshot-payload-v1';readonly component_kind:'repository_state_snapshot';readonly canonical_task_record:CanonicalSourceRefV1;readonly dispatch_record:CanonicalSourceRefV1}
export interface ValidationSnapshotPayloadV1 extends ComponentPayloadBaseV1 {readonly contract_version:'validation-snapshot-payload-v1';readonly component_kind:'validation_snapshot';readonly required_validation_refs:readonly CanonicalSourceRefV1[];readonly validation_bindings:readonly ValidationBindingV1[];readonly validation_facts:readonly HandoffFactV1[];readonly warning_fact_ids:readonly string[];readonly unverified_validation_ids:readonly string[]}
export type DecodedComponentPayloadV1=CompressedContextHandoffPayloadV1|ContextBootstrapPromptPayloadV1|CanonicalRecordManifestPayloadV1|RepositoryStateSnapshotPayloadV1|ValidationSnapshotPayloadV1
export interface GeneratedComponentV1 { readonly artifact:ComponentArtifactV1;readonly payload:DecodedComponentPayloadV1;readonly transport:{readonly component_kind:ComponentArtifactV1['component_kind'];readonly content_type:'application/json';readonly content_base64:string} }
/** Internal dynamic view used only after object/non-array admission. */
type ObjectFields={readonly [key:string]:unknown}
const fields=(v:unknown):ObjectFields|undefined=>typeof v==='object'&&v!==null&&!Array.isArray(v)?v as ObjectFields:undefined
const exact=(v:unknown,keys:readonly string[])=>{const x=fields(v);return x!==undefined&&Object.keys(x).length===keys.length&&keys.every(k=>Object.prototype.hasOwnProperty.call(x,k))}
const text=(v:unknown)=>typeof v==='string'&&v.length>0
const stableId=(v:unknown)=>typeof v==='string'&&v.length>0&&/^[A-Za-z0-9][A-Za-z0-9._:/-]*$/.test(v)
const utc=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v)&&!Number.isNaN(Date.parse(v))
const contentRef=(v:unknown)=>typeof v==='string'&&/^[A-Za-z0-9._/-]+\/sha256-[0-9a-f]{64}$/.test(v)
const all=(v:unknown,guard:(x:unknown)=>boolean)=>Array.isArray(v)&&v.every(guard)
const unique=(v:readonly string[])=>new Set(v).size===v.length
const safe=(s:string)=>!/(?:\b(?:secret|credential|token|password|authorization|stack)\b|[A-Za-z]:\\Users\\|https?:\/\/[^\s]+@)/i.test(s)
function canonical(v:unknown):string{if(v===null||typeof v==='boolean'||typeof v==='number'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';const x=fields(v);if(x===undefined)throw new TypeError('unsupported projection');return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}'}
async function hash(v:unknown,self:string,prefix:string){const input=fields(v);if(input===undefined)throw new TypeError('reference root must be an object');const x:{[key:string]:unknown}={...input};delete x[self];const bytes=new TextEncoder().encode(canonical(x));const d=await crypto.subtle.digest('SHA-256',bytes);return prefix+[...new Uint8Array(d)].map(n=>n.toString(16).padStart(2,'0')).join('')}
export const generateCheckpointRecordBuilderInputRef=(v:CheckpointRecordBuilderInputV1)=>hash(v,'checkpoint_record_builder_input_ref','evidence/context-health-checkpoint-builder-inputs/sha256-')
export const generateCheckpointRecordRef=(v:CheckpointRecordV1)=>hash(v,'checkpoint_record_ref','evidence/context-health-checkpoints/sha256-')
export const generateCheckpointRecordBuilderResultRef=(v:CheckpointRecordBuilderResultV1)=>hash(v,'checkpoint_record_builder_result_ref','evidence/context-health-checkpoint-builder-results/sha256-')
export const generateContextHandoffBundleBuilderInputRef=(v:ContextHandoffBundleBuilderInputV1)=>hash(v,'context_handoff_bundle_builder_input_ref','evidence/context-handoff-builder-inputs/sha256-')
export const generateContextHandoffBundleBuilderResultRef=(v:ContextHandoffBundleBuilderResultV1)=>hash(v,'context_handoff_bundle_builder_result_ref','evidence/context-handoff-builder-results/sha256-')
export async function verifyCheckpointRecordRef(v:CheckpointRecordV1){return v.checkpoint_record_ref===await generateCheckpointRecordRef(v)}
const baseInput=(v:unknown,version:string,reference:string)=>{const x=fields(v);return x!==undefined&&x.contract_version===version&&contentRef(x[reference])&&x.generator_contract_version===ARTIFACT_GENERATOR_VERSION&&utc(x.generated_at)}
const factValue=(v:unknown)=>{const x=fields(v);return x!==undefined&&(x.kind==='string'&&exact(v,['kind','string_value'])&&typeof x.string_value==='string'||x.kind==='integer'&&exact(v,['kind','integer_value'])&&Number.isInteger(x.integer_value)||x.kind==='boolean'&&exact(v,['kind','boolean_value'])&&typeof x.boolean_value==='boolean'||x.kind==='string_set'&&exact(v,['kind','string_values'])&&all(x.string_values,text)&&unique(x.string_values as string[])||x.kind==='reference'&&exact(v,['kind','reference_value'])&&validateCanonicalSourceRefV1(x.reference_value))}
const fact=(v:unknown)=>{const x=fields(v),sources=fields(v)?.source_refs,freshness=fields(v)?.freshness_evidence_ids,redactions=fields(v)?.redaction_record_ids,provenanceIds=fields(v)?.provenance_ids;if(x===undefined||!Array.isArray(sources)||!Array.isArray(freshness)||!Array.isArray(redactions)||!Array.isArray(provenanceIds)||!stableId(x.fact_id)||typeof x.fact_kind!=='string'||!['resolved','unresolved','blocked','not_applicable'].includes(x.resolution_state as string)||!['verified','unverified','stale','redacted'].includes(x.evidence_state as string)||typeof x.owner_role!=='string'||!all(sources,validateCanonicalSourceRefV1)||!all(freshness,stableId)||!all(redactions,stableId)||!all(provenanceIds,stableId)||!unique(sources.map(item=>JSON.stringify(item)))||!unique(freshness as string[])||!unique(redactions as string[])||!unique(provenanceIds as string[]))return false;const noValue=x.evidence_state==='unverified'||x.evidence_state==='redacted'||x.resolution_state==='not_applicable';if(exact(v,noValue?['fact_id','fact_kind','resolution_state','evidence_state','owner_role','source_refs','freshness_evidence_ids','redaction_record_ids','provenance_ids']:['fact_id','fact_kind','resolution_state','evidence_state','owner_role','value','source_refs','freshness_evidence_ids','redaction_record_ids','provenance_ids'])===false)return false;if(!noValue&&!factValue(x.value))return false;if(x.evidence_state==='verified'&&provenanceIds.length===0)return false;if(x.evidence_state==='unverified'&&(provenanceIds.length!==0||sources.length===0||x.resolution_state==='resolved'))return false;if(x.evidence_state==='stale'&&(provenanceIds.length===0||freshness.length===0||x.resolution_state==='resolved'))return false;if(x.evidence_state==='redacted'&&(provenanceIds.length===0||redactions.length===0||sources.length===0))return false;return x.resolution_state!=='not_applicable'||x.evidence_state==='verified'}
const provenance=(v:unknown)=>{const x=fields(v);return x!==undefined&&exact(v,['provenance_id','source_ref','source_kind','observed_at','verification_state','immutable_revision'])&&stableId(x.provenance_id)&&validateCanonicalSourceRefV1(x.source_ref)&&['github','repository','content_addressed'].includes(x.source_kind as string)&&utc(x.observed_at)&&['verified','contradicted'].includes(x.verification_state as string)&&fields(x.immutable_revision)!==undefined}
const workflow=(v:unknown)=>{const x=fields(v);return x!==undefined&&exact(v,['canonical_task_record','dispatch_record','issue_binding','pr_binding','branch_binding','worktree_binding','head_binding','execution_binding'])&&validateCanonicalSourceRefV1(x.canonical_task_record)&&validateCanonicalSourceRefV1(x.dispatch_record)&&['issue_binding','pr_binding','branch_binding','worktree_binding','head_binding','execution_binding'].every(key=>fields(x[key])!==undefined)}
const nextAction=(v:unknown)=>{const x=fields(v);return x!==undefined&&exact(v,['action_id','owner_role','action_summary','preconditions','source_refs'])&&stableId(x.action_id)&&typeof x.owner_role==='string'&&text(x.action_summary)&&all(x.preconditions,text)&&all(x.source_refs,validateCanonicalSourceRefV1)}
const componentBase=(v:unknown,version:string,kind:string)=>{const x=fields(v);return x!==undefined&&x.contract_version===version&&x.component_kind===kind&&contentRef(x.context_handoff_bundle_builder_input_ref)&&stableId(x.task_id)&&Number.isInteger(x.assignment_revision)&&(x.assignment_revision as number)>0&&typeof x.role==='string'&&x.repository==='whatrune/sd-prompt-studio'&&text(x.workflow_phase)&&stableId(x.checkpoint_instance_id)&&contentRef(x.context_health_decision_ref)&&utc(x.generated_at)&&x.generator_contract_version===ARTIFACT_GENERATOR_VERSION}
export function validateRedactionRecordV1(v:unknown):v is RedactionRecordV1{const x=fields(v);return x!==undefined&&exact(v,['redaction_record_id','redaction_code','affected_fact_ids','source_refs','basis_ref','disposition'])&&stableId(x.redaction_record_id)&&REDACTION_CODES.includes(x.redaction_code as RedactionCodeV1)&&Array.isArray(x.affected_fact_ids)&&x.affected_fact_ids.length>0&&all(x.affected_fact_ids,stableId)&&unique(x.affected_fact_ids as string[])&&Array.isArray(x.source_refs)&&x.source_refs.length>0&&all(x.source_refs,validateCanonicalSourceRefV1)&&validateCanonicalSourceRefV1(x.basis_ref)&&['source_detail_omitted','fact_value_removed'].includes(x.disposition as string)}
const annotation=(v:unknown)=>{const x=fields(v);return x!==undefined&&exact(v,['annotation_id','validation_id','annotation_kind','fact_id','source_refs'])&&stableId(x.annotation_id)&&stableId(x.validation_id)&&['warning','unverified_item'].includes(x.annotation_kind as string)&&stableId(x.fact_id)&&all(x.source_refs,validateCanonicalSourceRefV1)}
const repositoryState=(v:unknown)=>{const x=fields(v);if(x===undefined||x.repository!=='whatrune/sd-prompt-studio'||!workflow(x.workflow_identity_snapshot)||!utc(x.observed_at))return false;return x.state==='available'?exact(v,['state','repository','workflow_identity_snapshot','dirty_state','observed_at','evidence_refs'])&&['clean','dirty'].includes(x.dirty_state as string)&&all(x.evidence_refs,validateCanonicalSourceRefV1):x.state==='unavailable'?exact(v,['state','repository','workflow_identity_snapshot','observed_at','attempt'])&&(()=>{const a=fields(x.attempt);return a!==undefined&&exact(a,['attempt_id'])&&stableId(a.attempt_id)})():false}
const admittedContext=(x:ObjectFields)=>validateContextHealthPolicyV1(x.context_health_policy,x.generated_at as string).accepted&&validateContextHealthEvaluationInputV1(x.context_health_evaluation_input,x.generated_at as string).accepted&&validateContextHealthDecisionV1(x.context_health_decision,x.generated_at as string).accepted
export function validateCheckpointRecordBuilderInputV1(v:unknown):v is CheckpointRecordBuilderInputV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','checkpoint_record_builder_input_ref','context_health_policy','context_health_evaluation_input','context_health_decision','material_facts','redaction_records','source_provenance','generated_at','generator_contract_version'])&&baseInput(v,CHECKPOINT_RECORD_BUILDER_INPUT_VERSION,'checkpoint_record_builder_input_ref')&&admittedContext(x)&&Array.isArray(x.material_facts)&&all(x.material_facts,fact)&&all(x.redaction_records,validateRedactionRecordV1)&&all(x.source_provenance,provenance)}
export function validateContextHandoffBundleBuilderInputV1(v:unknown):v is ContextHandoffBundleBuilderInputV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','context_handoff_bundle_builder_input_ref','context_health_policy','context_health_evaluation_input','context_health_decision','canonical_task_record','dispatch_record','workflow_identity_snapshot','completed_work','frozen_decisions','unresolved_items','blockers_and_risks','forbidden_operations','exact_next_action','validation_annotations','material_facts','freshness_evidence','redaction_records','source_provenance','repository_state','generated_at','generator_contract_version'])&&baseInput(v,CONTEXT_HANDOFF_BUNDLE_BUILDER_INPUT_VERSION,'context_handoff_bundle_builder_input_ref')&&admittedContext(x)&&validateCanonicalSourceRefV1(x.canonical_task_record)&&validateCanonicalSourceRefV1(x.dispatch_record)&&workflow(x.workflow_identity_snapshot)&&all(x.completed_work,fact)&&all(x.frozen_decisions,fact)&&all(x.unresolved_items,fact)&&all(x.blockers_and_risks,fact)&&all(x.forbidden_operations,fact)&&nextAction(x.exact_next_action)&&all(x.validation_annotations,annotation)&&all(x.material_facts,fact)&&all(x.freshness_evidence,fact)&&all(x.redaction_records,validateRedactionRecordV1)&&all(x.source_provenance,provenance)&&repositoryState(x.repository_state)}
export function validateCheckpointRecordV1(v:unknown):v is CheckpointRecordV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','checkpoint_record_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','checkpoint_type','canonical_task_record','dispatch_record','context_health_policy_ref','context_health_input_ref','context_health_decision_ref','checkpoint_rule_ref','protected_action_ref','outcome','legal_action_class','required_artifact_class','soft_score','material_facts','unresolved_items','redaction_records','source_provenance','generator_contract_version','generated_at'])&&x.contract_version===CHECKPOINT_RECORD_VERSION&&contentRef(x.checkpoint_record_ref)&&stableId(x.task_id)&&Number.isInteger(x.assignment_revision)&&typeof x.role==='string'&&x.repository==='whatrune/sd-prompt-studio'&&text(x.workflow_phase)&&stableId(x.checkpoint_instance_id)&&text(x.checkpoint_type)&&validateCanonicalSourceRefV1(x.canonical_task_record)&&validateCanonicalSourceRefV1(x.dispatch_record)&&contentRef(x.context_health_policy_ref)&&contentRef(x.context_health_input_ref)&&contentRef(x.context_health_decision_ref)&&stableId(x.checkpoint_rule_ref)&&validateCanonicalSourceRefV1(x.protected_action_ref)&&x.outcome==='checkpoint_only'&&x.legal_action_class==='assigned_work_allowed'&&x.required_artifact_class==='checkpoint_record'&&Number.isInteger(x.soft_score)&&all(x.material_facts,fact)&&all(x.unresolved_items,fact)&&all(x.redaction_records,validateRedactionRecordV1)&&all(x.source_provenance,provenance)&&x.generator_contract_version===ARTIFACT_GENERATOR_VERSION&&utc(x.generated_at)}
export function validateCompletenessIssueV1(v:unknown):v is CompletenessIssueV1{const x=fields(v);return x!==undefined&&exact(v,['issue_id','code','path','affected_ids','evidence_refs','decision_owner','retry_policy'])&&stableId(x.issue_id)&&COMPLETENESS_ISSUE_CODES.includes(x.code as CompletenessIssueV1['code'])&&text(x.path)&&Array.isArray(x.affected_ids)&&all(x.affected_ids,stableId)&&unique(x.affected_ids as string[])&&Array.isArray(x.evidence_refs)&&all(x.evidence_refs,validateCanonicalSourceRefV1)&&x.decision_owner==='integrated_lead'&&x.retry_policy==='after_input_correction'}
export function validateArtifactBuilderFailureV1(v:unknown):v is ArtifactBuilderFailureV1{const x=fields(v);return x!==undefined&&exact(v,['failure_code','failure_stage','path','message','verified_refs','decision_owner','retry_policy'])&&ARTIFACT_BUILDER_FAILURE_CODES.includes(x.failure_code as ArtifactBuilderFailureV1['failure_code'])&&['admission','identity','completeness_admission','projection','component_generation','reference_generation','internal'].includes(x.failure_stage as string)&&text(x.path)&&text(x.message)&&all(x.verified_refs,validateCanonicalSourceRefV1)&&typeof x.decision_owner==='string'&&['after_input_correction','after_architect_decision','after_implementation_fix'].includes(x.retry_policy as string)}
export function validateCheckpointRecordBuilderResultV1(v:unknown):v is CheckpointRecordBuilderResultV1{const x=fields(v);if(x===undefined||x.contract_version!==CHECKPOINT_RECORD_BUILDER_RESULT_VERSION||x.publication_performed!==false||!contentRef(x.checkpoint_record_builder_result_ref))return false;return x.result_kind==='complete'?exact(v,['contract_version','checkpoint_record_builder_result_ref','result_kind','checkpoint_record_builder_input_ref','checkpoint_record','publication_performed'])&&contentRef(x.checkpoint_record_builder_input_ref)&&validateCheckpointRecordV1(x.checkpoint_record):x.result_kind==='incomplete'?exact(v,['contract_version','checkpoint_record_builder_result_ref','result_kind','checkpoint_record_builder_input_ref','completeness_issues','publication_performed'])&&contentRef(x.checkpoint_record_builder_input_ref)&&Array.isArray(x.completeness_issues)&&x.completeness_issues.length>0&&all(x.completeness_issues,validateCompletenessIssueV1):x.result_kind==='failure'?exact(v,['contract_version','checkpoint_record_builder_result_ref','result_kind','failure','publication_performed'])&&validateArtifactBuilderFailureV1(x.failure):false}
export function validateArtifactSafeProjection(v:unknown):boolean{return safe(canonical(v))}
export function validateCompressedContextHandoffPayloadV1(v:unknown):v is CompressedContextHandoffPayloadV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','component_kind','context_handoff_bundle_builder_input_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','context_health_decision_ref','generated_at','generator_contract_version','canonical_task_record','workflow_identity_snapshot','completed_work','frozen_decisions','unresolved_items','blockers_and_risks','forbidden_operations','validation_fact_ids','exact_next_action','freshness_evidence','redaction_records','source_provenance'])&&componentBase(v,'compressed-context-handoff-payload-v1','compressed_context_handoff')&&validateCanonicalSourceRefV1(x.canonical_task_record)&&workflow(x.workflow_identity_snapshot)&&all(x.completed_work,fact)&&all(x.frozen_decisions,fact)&&all(x.unresolved_items,fact)&&all(x.blockers_and_risks,fact)&&all(x.forbidden_operations,fact)&&all(x.validation_fact_ids,stableId)&&unique(x.validation_fact_ids as string[])&&nextAction(x.exact_next_action)&&all(x.freshness_evidence,fact)&&all(x.redaction_records,validateRedactionRecordV1)&&all(x.source_provenance,provenance)}
export function validateContextBootstrapPromptPayloadV1(v:unknown):v is ContextBootstrapPromptPayloadV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','component_kind','context_handoff_bundle_builder_input_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','context_health_decision_ref','generated_at','generator_contract_version','canonical_task_record','expected_manifest_contract_version','exact_next_action','unresolved_item_ids','blocker_fact_ids','instruction_sequence','stop_conditions'])&&componentBase(v,'context-bootstrap-prompt-payload-v1','bootstrap_prompt')&&validateCanonicalSourceRefV1(x.canonical_task_record)&&x.expected_manifest_contract_version==='context-handoff-manifest-v1'&&nextAction(x.exact_next_action)&&all(x.unresolved_item_ids,stableId)&&unique(x.unresolved_item_ids as string[])&&all(x.blocker_fact_ids,stableId)&&unique(x.blocker_fact_ids as string[])&&Array.isArray(x.instruction_sequence)&&x.instruction_sequence.length===BOOTSTRAP_INSTRUCTION_SEQUENCE.length&&x.instruction_sequence.every((item,index)=>item===BOOTSTRAP_INSTRUCTION_SEQUENCE[index])&&Array.isArray(x.stop_conditions)&&x.stop_conditions.length===BOOTSTRAP_STOP_CONDITIONS.length&&x.stop_conditions.every((item,index)=>item===BOOTSTRAP_STOP_CONDITIONS[index])}
export function validateCanonicalRecordManifestPayloadV1(v:unknown):v is CanonicalRecordManifestPayloadV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','component_kind','context_handoff_bundle_builder_input_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','context_health_decision_ref','generated_at','generator_contract_version','canonical_task_record','dispatch_record','policy_ref','evaluation_input_ref','decision_ref','fact_source_bindings','source_provenance','redaction_records'])&&componentBase(v,'canonical-record-manifest-payload-v1','canonical_record_manifest')&&validateCanonicalSourceRefV1(x.canonical_task_record)&&validateCanonicalSourceRefV1(x.dispatch_record)&&contentRef(x.policy_ref)&&contentRef(x.evaluation_input_ref)&&contentRef(x.decision_ref)&&all(x.fact_source_bindings,binding=>{const b=fields(binding);return b!==undefined&&exact(binding,['fact_id','source_refs','provenance_ids','freshness_evidence_ids','redaction_record_ids'])&&stableId(b.fact_id)&&all(b.source_refs,validateCanonicalSourceRefV1)&&all(b.provenance_ids,stableId)&&all(b.freshness_evidence_ids,stableId)&&all(b.redaction_record_ids,stableId)})&&all(x.source_provenance,provenance)&&all(x.redaction_records,validateRedactionRecordV1)}
export function validateRepositoryStateSnapshotPayloadV1(v:unknown):v is RepositoryStateSnapshotPayloadV1{const x=fields(v);if(x===undefined||!componentBase(v,'repository-state-snapshot-payload-v1','repository_state_snapshot')||!validateCanonicalSourceRefV1(x.canonical_task_record)||!validateCanonicalSourceRefV1(x.dispatch_record)||!workflow(x.workflow_identity_snapshot)||x.repository!=='whatrune/sd-prompt-studio'||!utc(x.observed_at))return false;return x.state==='available'?exact(v,['contract_version','component_kind','context_handoff_bundle_builder_input_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','context_health_decision_ref','generated_at','generator_contract_version','state','workflow_identity_snapshot','dirty_state','observed_at','evidence_refs','canonical_task_record','dispatch_record'])&&['clean','dirty'].includes(x.dirty_state as string)&&all(x.evidence_refs,validateCanonicalSourceRefV1):x.state==='unavailable'?exact(v,['contract_version','component_kind','context_handoff_bundle_builder_input_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','context_health_decision_ref','generated_at','generator_contract_version','state','workflow_identity_snapshot','observed_at','attempt','canonical_task_record','dispatch_record'])&&fields(x.attempt)!==undefined&&stableId(fields(x.attempt)?.attempt_id):false}
export function validateValidationSnapshotPayloadV1(v:unknown):v is ValidationSnapshotPayloadV1{const x=fields(v);return x!==undefined&&exact(v,['contract_version','component_kind','context_handoff_bundle_builder_input_ref','task_id','assignment_revision','role','repository','workflow_phase','checkpoint_instance_id','context_health_decision_ref','generated_at','generator_contract_version','required_validation_refs','validation_bindings','validation_facts','warning_fact_ids','unverified_validation_ids'])&&componentBase(v,'validation-snapshot-payload-v1','validation_snapshot')&&all(x.required_validation_refs,validateCanonicalSourceRefV1)&&Array.isArray(x.validation_bindings)&&all(x.validation_facts,fact)&&all(x.warning_fact_ids,stableId)&&unique(x.warning_fact_ids as string[])&&all(x.unverified_validation_ids,stableId)&&unique(x.unverified_validation_ids as string[])}
export function validateGeneratedComponentV1(v:unknown):v is GeneratedComponentV1{const x=fields(v);if(x===undefined||!exact(v,['artifact','payload','transport']))return false;const artifact=fields(x.artifact),transport=fields(x.transport),payload=fields(x.payload);if(artifact===undefined||transport===undefined||payload===undefined||!exact(artifact,['component_id','component_kind','content_type','byte_length','sha256'])||!exact(transport,['component_kind','content_type','content_base64'])||!stableId(artifact.component_id)||typeof artifact.component_kind!=='string'||artifact.content_type!=='application/json'||!Number.isInteger(artifact.byte_length)||(artifact.byte_length as number)<0||typeof artifact.sha256!=='string'||! /^[0-9a-f]{64}$/.test(artifact.sha256)||transport.component_kind!==artifact.component_kind||transport.content_type!=='application/json'||typeof transport.content_base64!=='string'||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(transport.content_base64))return false;return validateCompressedContextHandoffPayloadV1(payload)||validateContextBootstrapPromptPayloadV1(payload)||validateCanonicalRecordManifestPayloadV1(payload)||validateRepositoryStateSnapshotPayloadV1(payload)||validateValidationSnapshotPayloadV1(payload)}
const bytesEqual=(left:Uint8Array,right:Uint8Array)=>left.length===right.length&&left.every((value,index)=>value===right[index])
const decode=(value:string)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0))
export async function verifyGeneratedComponentIntegrityV1(v:unknown):Promise<boolean>{if(!validateGeneratedComponentV1(v))return false;const canonicalBytes=new TextEncoder().encode(canonical(v.payload));let decoded:Uint8Array;try{decoded=decode(v.transport.content_base64)}catch{return false}if(!bytesEqual(decoded,canonicalBytes)||v.artifact.byte_length!==canonicalBytes.length)return false;const digestBytes=await crypto.subtle.digest('SHA-256',canonicalBytes);const digest=[...new Uint8Array(digestBytes)].map(value=>value.toString(16).padStart(2,'0')).join('');return v.artifact.sha256===digest&&v.artifact.component_id===`${v.artifact.component_kind}/sha256-${digest}`&&v.payload.component_kind===v.artifact.component_kind}
const ORDER=['compressed_context_handoff','bootstrap_prompt','canonical_record_manifest','repository_state_snapshot','validation_snapshot'] as const
export function validateContextHandoffBundleBuilderResultV1(v:unknown):v is ContextHandoffBundleBuilderResultV1{const x=fields(v);if(x===undefined||x.contract_version!==CONTEXT_HANDOFF_BUNDLE_BUILDER_RESULT_VERSION||x.publication_performed!==false||!contentRef(x.context_handoff_bundle_builder_result_ref))return false;if(x.result_kind==='complete'){if(!exact(v,['contract_version','context_handoff_bundle_builder_result_ref','result_kind','context_handoff_bundle_builder_input_ref','context_handoff_manifest','generated_components','publication_performed'])||!contentRef(x.context_handoff_bundle_builder_input_ref)||!Array.isArray(x.generated_components)||x.generated_components.length!==ORDER.length||!x.generated_components.every(validateGeneratedComponentV1))return false;const manifest=fields(x.context_handoff_manifest),components=manifest===undefined?undefined:manifest.component_artifacts,validation=manifest===undefined?undefined:fields(manifest.validation_snapshot);if(!Array.isArray(components)||components.length!==ORDER.length||validation===undefined)return false;return x.generated_components.every((component,index)=>{const listed=fields(components[index]);return component.artifact.component_kind===ORDER[index]&&listed!==undefined&&listed.component_id===component.artifact.component_id&&listed.sha256===component.artifact.sha256&&listed.byte_length===component.artifact.byte_length})&&validation.component_id===x.generated_components[4].artifact.component_id}return x.result_kind==='incomplete'?exact(v,['contract_version','context_handoff_bundle_builder_result_ref','result_kind','context_handoff_bundle_builder_input_ref','completeness_issues','publication_performed'])&&contentRef(x.context_handoff_bundle_builder_input_ref)&&Array.isArray(x.completeness_issues)&&x.completeness_issues.length>0&&all(x.completeness_issues,validateCompletenessIssueV1):x.result_kind==='failure'?exact(v,['contract_version','context_handoff_bundle_builder_result_ref','result_kind','failure','publication_performed'])&&validateArtifactBuilderFailureV1(x.failure):false}
export async function verifyContextHandoffBundleBuilderResultIntegrityV1(v:unknown):Promise<boolean>{if(!validateContextHandoffBundleBuilderResultV1(v))return false;if(v.result_kind!=='complete')return true;const generated=v.generated_components;if(!(await Promise.all(generated.map(verifyGeneratedComponentIntegrityV1))).every(Boolean))return false;const manifest=validateContextHandoffManifestV1(v.context_handoff_manifest,v.context_handoff_manifest.generated_at);return manifest.accepted&&manifest.value.component_artifacts.every((artifact,index)=>artifact.component_id===generated[index].artifact.component_id&&artifact.sha256===generated[index].artifact.sha256&&artifact.byte_length===generated[index].artifact.byte_length)}
export function freeze<T>(v:T):DeepReadonly<T>{return deepFreezeClone(v)}
