import { ROLE_VALUES, type RoleV1 } from '../context-health'

export const AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION = 'automatic-gate-progression-evaluation-v1' as const
export const AUTOMATIC_GATE_PROGRESSION_INPUT_VERSION = 'automatic-gate-progression-evaluation-input-v1' as const
type Url = string
type Head = string
export type GateStatusValueV1 = 'completed'|'historical_at_prior_head'|'pending'|'blocked'|'unperformed'
export type ExecutionStopReasonV1 = 'architecture_gap'|'external_blocker'

export interface AutomaticGateProgressionEvaluationInputV1 {
  readonly contract_version: typeof AUTOMATIC_GATE_PROGRESSION_INPUT_VERSION
  readonly task_id:string; readonly repository:'whatrune/sd-prompt-studio'; readonly assignment_revision:number; readonly evaluated_at:string
  readonly task_assignment:{readonly canonical_record:Url;readonly assigned_role:RoleV1;readonly allowed_actions:readonly string[];readonly forbidden_actions:readonly string[];readonly completion_conditions:readonly string[];readonly escalation_conditions:readonly string[];readonly next_transition?:{readonly target_role:RoleV1;readonly next_action:string;readonly protected_action?:'ready_for_review'|'approve'|'merge'}}
  readonly result_handoff:{readonly canonical_record:Url;readonly authoring_role:RoleV1;readonly status:'completed'|'blocked'|'needs_followup';readonly execution_stop_reason:'completed'|ExecutionStopReasonV1;readonly execution_head:Head;readonly recommended_next_action?:string}
  readonly review_decision:{readonly canonical_record:Url;readonly reviewed_pr:Url;readonly reviewed_head:Head;readonly decision:'approved'|'needs_followup'|'blocked';readonly blocking_findings:readonly {readonly finding_id:string;readonly state:'open'|'reopened'|'closed'}[];readonly correction?:{readonly target_role:RoleV1;readonly next_action:string}}
  readonly pr:{readonly url:Url;readonly head:Head;readonly base:Head;readonly state:'open'|'closed';readonly draft:boolean;readonly blocking_findings:readonly string[]}
  readonly checks:readonly {readonly name:string;readonly url:Url;readonly conclusion:'success'|'failure'|'pending';readonly checked_head:Head}[]
  readonly review_threads:readonly {readonly url:Url;readonly state:'resolved'|'unresolved';readonly outdated:boolean;readonly blocking:boolean}[]
  readonly gate_status:{readonly projected_head:Head;readonly rows:readonly {readonly gate:string;readonly value:GateStatusValueV1;readonly citation_urls:readonly Url[]}[];readonly current_blocker?:string;readonly next_gate_owner?:RoleV1}
  readonly workspace:{readonly branch:string;readonly worktree:string;readonly head:Head;readonly clean:boolean;readonly available:boolean}
  readonly context_health:{readonly required:boolean;readonly admitted:boolean;readonly canonical_record?:Url}
  readonly approval?:{readonly canonical_record:Url;readonly action:'ready_for_review'|'approve'|'merge';readonly task_id:string;readonly pr:Url;readonly approved_head:Head;readonly approved_base:Head;readonly approved_state:'open'|'closed';readonly state:'current'|'expired'|'consumed'|'invalid'}
}

type Common={readonly contract_version:typeof AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION;readonly kind:string;readonly task_id:string;readonly evaluated_at:string;readonly input_fingerprint:string;readonly precedence_trace:readonly string[];readonly gate_status_requirement:GateStatusRequirementV1}
export type GateStatusRequirementV1={readonly required:false}|{readonly required:true;readonly authorized_metadata_role:RoleV1;readonly pr:Url;readonly current_head:Head;readonly required_gate_fields:readonly string[];readonly citation_urls:readonly Url[];readonly reason:'missing'|'stale'|'conflicting'|'historical_at_prior_head';readonly must_verify_after_write:true;readonly current_blocker?:string;readonly next_gate_owner?:RoleV1}
export type AutomaticGateProgressionEvaluationResultV1=
 | (Common&{readonly kind:'recommend_next_role';readonly target_role:RoleV1;readonly next_action:string;readonly predecessor_canonical_url:Url;readonly target_head:Head;readonly same_task_id:string;readonly idempotency_key:string})
 | (Common&{readonly kind:'wait_for_protected_action';readonly protected_action:'ready_for_review'|'approve'|'merge';readonly wait_reason:'approval_missing_or_not_current';readonly required_approval_fields:readonly string[];readonly required_head:Head;readonly required_base:Head;readonly required_pr:Url})
 | (Common&{readonly kind:'require_gate_status_update';readonly requirement:Exclude<GateStatusRequirementV1,{readonly required:false}>})
 | (Common&{readonly kind:'invalidate_approval';readonly approval_record:Url;readonly invalidation_reason:'head_drift'|'base_or_state_drift'|'check_drift'|'blocking_recurrence'|'invalid_approval';readonly historical_evidence_refs:readonly Url[];readonly required_fresh_gates:readonly string[]})
 | (Common&{readonly kind:'stop';readonly stop_condition:string;readonly execution_stop_reason:ExecutionStopReasonV1;readonly canonical_evidence_refs:readonly Url[];readonly recovery_owner:RoleV1;readonly required_recovery_evidence:readonly string[]})
 | (Common&{readonly kind:'no_transition';readonly wait_reason:'no_declared_transition';readonly required_future_canonical_event:string})

const roles=new Set<string>(ROLE_VALUES)
const url=(v:unknown):v is Url=>typeof v==='string'&&/^https:\/\/github\.com\/whatrune\/sd-prompt-studio\//.test(v)
const head=(v:unknown):v is Head=>typeof v==='string'&&/^[0-9a-f]{40}$/.test(v)
const utc=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{3})?Z$/.test(v)
const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const keys=(v:Record<string,unknown>,wanted:readonly string[])=>Object.keys(v).length===wanted.length&&wanted.every(k=>Object.prototype.hasOwnProperty.call(v,k))
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'){Object.freeze(v);for(const x of Object.values(v as Record<string,unknown>))freeze(x)}return v}
const canon=(v:unknown):string=>Array.isArray(v)?`[${v.map(canon).join(',')}]`:object(v)?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`:JSON.stringify(v)
const byte=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);for(let i=0;i<Math.min(x.length,y.length);i++){const d=x[i]-y[i];if(d)return d}return x.length-y.length}
const sorted=(values:readonly string[])=>[...values].sort(byte)
const unique=(values:readonly string[])=>new Set(values).size===values.length

function stop(task_id:string,evaluated_at:string,input_fingerprint:string,trace:readonly string[],condition:string,reason:ExecutionStopReasonV1,refs:readonly Url[],owner:RoleV1):AutomaticGateProgressionEvaluationResultV1{return freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'stop',task_id,evaluated_at,input_fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},stop_condition:condition,execution_stop_reason:reason,canonical_evidence_refs:sorted(refs),recovery_owner:owner,required_recovery_evidence:['fresh_direct_canonical_record']})}

const malformed=(input:unknown):{readonly task_id:string;readonly evaluated_at:string;readonly fingerprint:string}=>object(input)?{task_id:typeof input.task_id==='string'?input.task_id:'unknown_task',evaluated_at:typeof input.evaluated_at==='string'?input.evaluated_at:'1970-01-01T00:00:00Z',fingerprint:canon(input)}:{task_id:'unknown_task',evaluated_at:'1970-01-01T00:00:00Z',fingerprint:canon(input)}
function validInput(x:AutomaticGateProgressionEvaluationInputV1):boolean{const root=x as unknown as Record<string,unknown>,base=['contract_version','task_id','repository','assignment_revision','evaluated_at','task_assignment','result_handoff','review_decision','pr','checks','review_threads','gate_status','workspace','context_health'];if(!keys(root,'approval' in root?[...base,'approval']:base)||x.contract_version!==AUTOMATIC_GATE_PROGRESSION_INPUT_VERSION||!x.task_id||x.repository!=='whatrune/sd-prompt-studio'||!Number.isInteger(x.assignment_revision)||!utc(x.evaluated_at)||!url(x.task_assignment.canonical_record)||!roles.has(x.task_assignment.assigned_role)||!url(x.result_handoff.canonical_record)||!roles.has(x.result_handoff.authoring_role)||!head(x.result_handoff.execution_head)||!url(x.review_decision.canonical_record)||!url(x.review_decision.reviewed_pr)||!head(x.review_decision.reviewed_head)||!url(x.pr.url)||!head(x.pr.head)||!head(x.pr.base)||!head(x.workspace.head)||!x.workspace.branch||!x.workspace.worktree)return false;const ids=x.review_decision.blocking_findings.map(v=>v.finding_id),checks=x.checks.map(v=>`${v.name}\u0000${v.url}`),threads=x.review_threads.map(v=>v.url);return unique(ids)&&unique(checks)&&unique(threads)&&x.checks.every(v=>url(v.url)&&head(v.checked_head))&&x.review_threads.every(v=>url(v.url))&&x.gate_status.rows.every(v=>unique(v.citation_urls)&&v.citation_urls.every(url))}

export function evaluateAutomaticGateProgressionV1(input:unknown):AutomaticGateProgressionEvaluationResultV1{try{const m=malformed(input);if(!object(input)||!validInput(input as unknown as AutomaticGateProgressionEvaluationInputV1))return stop(m.task_id,m.evaluated_at,m.fingerprint,['input_admission'],'malformed_or_unknown_input','architecture_gap',[],'backend_architect');const x=input as unknown as AutomaticGateProgressionEvaluationInputV1,fingerprint=canon(x),trace:string[]=[];const refs=[x.task_assignment.canonical_record,x.result_handoff.canonical_record,x.review_decision.canonical_record];
  trace.push('input_admission');if(x.result_handoff.execution_head!==x.pr.head||x.review_decision.reviewed_head!==x.pr.head||x.workspace.head!==x.pr.head)return x.approval?freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'invalidate_approval',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},approval_record:x.approval.canonical_record,invalidation_reason:'head_drift',historical_evidence_refs:sorted(refs),required_fresh_gates:['result_handoff','review_decision','exact_head_checks']}) : stop(x.task_id,x.evaluated_at,fingerprint,trace,'head_identity_drift','external_blocker',refs,'integrated_lead');
  trace.push('canonical_precedence');if(x.review_decision.reviewed_pr!==x.pr.url||x.result_handoff.status==='blocked'||x.review_decision.decision==='blocked')return stop(x.task_id,x.evaluated_at,fingerprint,trace,'canonical_conflict','architecture_gap',refs,'backend_architect');if(x.context_health.required&&(!x.context_health.admitted||!x.context_health.canonical_record))return stop(x.task_id,x.evaluated_at,fingerprint,trace,'required_context_health_unavailable','external_blocker',refs,'integrated_lead');
  trace.push('fresh_state');if(!x.workspace.available||!x.workspace.clean||x.pr.state!=='open'||x.checks.length===0||x.checks.some(v=>v.conclusion!=='success'||v.checked_head!==x.pr.head))return x.approval?freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'invalidate_approval',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},approval_record:x.approval.canonical_record,invalidation_reason:'check_drift',historical_evidence_refs:sorted(refs),required_fresh_gates:['clean_workspace','exact_head_checks']}) : stop(x.task_id,x.evaluated_at,fingerprint,trace,'fresh_evidence_unavailable','external_blocker',refs,'integrated_lead');
  if(x.pr.blocking_findings.length||x.review_decision.blocking_findings.some(v=>v.state!=='closed')||x.review_threads.some(v=>v.blocking&&!v.outdated&&v.state==='unresolved'))return x.approval?freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'invalidate_approval',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},approval_record:x.approval.canonical_record,invalidation_reason:'blocking_recurrence',historical_evidence_refs:sorted(refs),required_fresh_gates:['review_decision','blocking_findings']}) : stop(x.task_id,x.evaluated_at,fingerprint,trace,'blocking_finding_recurrence','external_blocker',refs,'integrated_lead');
  trace.push('gate_status');const requirement:Exclude<GateStatusRequirementV1,{readonly required:false}>={required:true,authorized_metadata_role:x.task_assignment.assigned_role,pr:x.pr.url,current_head:x.pr.head,required_gate_fields:['current_head','final_regression','operational_validation','pr_state','draft_state','ready','approve','merge','next_gate_owner'],citation_urls:sorted(refs),reason:x.gate_status.projected_head===x.pr.head?'conflicting':'stale',must_verify_after_write:true,current_blocker:x.gate_status.current_blocker,next_gate_owner:x.gate_status.next_gate_owner};if(x.gate_status.projected_head!==x.pr.head||x.gate_status.rows.length===0)return freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'require_gate_status_update',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:requirement,requirement});
  trace.push('transition');const candidate=x.review_decision.correction??x.task_assignment.next_transition;if(!candidate)return freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'no_transition',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},wait_reason:'no_declared_transition',required_future_canonical_event:'direct_same_task_decision'});const next:{readonly target_role:RoleV1;readonly next_action:string;readonly protected_action?:'ready_for_review'|'approve'|'merge'}=candidate;if(next.protected_action){if(!x.approval||x.approval.state!=='current'||x.approval.action!==next.protected_action||x.approval.task_id!==x.task_id||x.approval.pr!==x.pr.url||x.approval.approved_head!==x.pr.head||x.approval.approved_base!==x.pr.base||x.approval.approved_state!==x.pr.state)return freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'wait_for_protected_action',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},protected_action:next.protected_action,wait_reason:'approval_missing_or_not_current',required_approval_fields:['canonical_record','task_id','pr','approved_head','approved_base','approved_state'],required_head:x.pr.head,required_base:x.pr.base,required_pr:x.pr.url});return freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'wait_for_protected_action',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},protected_action:next.protected_action,wait_reason:'approval_missing_or_not_current',required_approval_fields:['separately_authorized_executor'],required_head:x.pr.head,required_base:x.pr.base,required_pr:x.pr.url})}
  const predecessor=x.review_decision.canonical_record,key=[x.task_id,String(x.assignment_revision),predecessor,next.target_role,next.next_action,x.pr.head].join('|');return freeze({contract_version:AUTOMATIC_GATE_PROGRESSION_EVALUATION_VERSION,kind:'recommend_next_role',task_id:x.task_id,evaluated_at:x.evaluated_at,input_fingerprint:fingerprint,precedence_trace:trace,gate_status_requirement:{required:false},target_role:next.target_role,next_action:next.next_action,predecessor_canonical_url:predecessor,target_head:x.pr.head,same_task_id:x.task_id,idempotency_key:key})
 }catch{return stop('unknown_task','1970-01-01T00:00:00Z','{}',['internal_failure'],'internal_evaluation_failure','external_blocker',[],'integrated_lead')}}
